### ISSUE TITLE
build.sh uses bash feature incompatible with OS X

### ISSUE THREAD

**Issue by dlbewley** [sclorg/s2i-python-container#104]
The version of `/bin/bash` on OS X as late as 10.11.3 does not support `[[`.

**Error:** `hack/build.sh: line 73: conditional binary operator expected`

The change below would seem to make it compatible, but you may have a reason you didn't already do this. I understand if you just close this issue.

```
diff --git a/hack/build.sh b/hack/build.sh
index c62825b..cd2e272 100755
--- a/hack/build.sh
+++ b/hack/build.sh
@@ -70,7 +70,7 @@ for dir in ${dirs}; do

   IMAGE_NAME="${NAMESPACE}${BASE_IMAGE_NAME}-${dir//./}-${OS}"

-  if [[ -v TEST_MODE ]]; then
+  if [ -n "$TEST_MODE" ]; then
     IMAGE_NAME+="-candidate"
   fi

@@ -83,7 +83,7 @@ for dir in ${dirs}; do
     docker_build_with_version Dockerfile
   fi

-  if [[ -v TEST_MODE ]]; then
+  if [ -n "$TEST_MODE" ]; then
     IMAGE_NAME=${IMAGE_NAME} test/run

     if [[ $? -eq 0 ]] && [[ "${TAG_ON_SUCCESS}" == "true" ]]; then
```

**Comment by mfojtik** [comment]
@bparees @csrwng i think we should fix this for all scripts in all our images, right?

**Comment by csrwng** [comment]
yes :+1:

**Comment by csrwng** [comment]
I haven't run into this because I usually replace the default OS X bash with the latest one installed from brew.

**Comment by mnagy** [comment]
@dlbewley [ also supports -v. Does OS X bash not support -v? If not, then I suggest we use `-n "${TEST_MODE:-}"`, at least in scripts that do not tolerate usage of unset variables.

**Comment by bparees** [comment]
though it's a bit religious, [[ seems to be generally preferred(more full featured) and not all that new, i'm surprised OSX has an issue:

http://stackoverflow.com/questions/669452/is-preferable-over-in-bash-scripts

but I won't stand in the way if one of you mac users wants to fix it :)

**Comment by mfojtik** [comment]
@bparees yeah, I prefer `[[` as well... but recently I learned OSX bash sux :-) (unless you install the latest bash from homebrew, which is what I'm doing ;-)

**Comment by dlbewley** [comment]
@mnagy `[ -v TEST ]` does not seems to work for me on OS X.

`hack/build.sh: line 73: [: -v: unary operator expected`

If `[[` is preferred and the convention, it seems reasonable to require OS X users to update bash with _homebrew_ or use a linux VM. They are already jumping through some amount of hoops to get docker running.

I leave it to your expert opinions.

**Comment by GrahamDumpleton** [comment]
FWIW, even upcoming MacOS X High Sierra will still have the same old bash version, likely because newer versions use GPL V3. Personally I don't like installing bash through Homebrew, as as a developer who releases my own packages, I need to ensure I am writing scripts which will work with the system bash version. 

My preference therefore is to use syntax that works with older bash version. Since I need to get ability to build working on MacOS X to test some of the current PRs, I'll create a PR to use older syntax.

**Comment by pkubatrh** [comment]
AFAIK this should be fixed for some time already (in `build.sh` at least) since we had a similar request for this over at https://github.com/sclorg/container-common-scripts/pull/17

**Comment by GrahamDumpleton** [comment]
Okay. Seems have moved to git sub modules for the stuff as well so not even in this repo anymore.

So can someone close this then if has been addressed.
