### ISSUE TITLE
Why are these under SCLORG org?

### ISSUE THREAD

**Issue by jfmatth** [sclorg/s2i-python-container#128]
Just curious why these repo's aren't part of the Openshift Org?

**Comment by bparees** [comment]
The SCL team now maintains these images since the images package rpms maintained by the SCL team and the intent is that these docker images could be used by anyone looking to consume the SCL packages in a docker form, not just openshift users.

**Comment by jfmatth** [comment]
Ben, thank you for the quick response, and I'm glad to see the logic behind this.

What does SCL stand for?

**Comment by bparees** [comment]
Software Collections (Library?)
https://access.redhat.com/documentation/en-US/Red_Hat_Developer_Toolset/1/html-single/Software_Collections_Guide/
