### ISSUE TITLE
Question - What is the web server for python container

### ISSUE THREAD

**Issue by jfmatth** [sclorg/s2i-python-container#129]
I had a question about what web server is in the container, if any?

Does the port 80 or 443 call get answered by GUNICORN directly, or is it handled by Apache and then given to GUNICORN as WSGI?

thanks,

J

**Comment by bparees** [comment]
gunicorn directly:
https://github.com/sclorg/s2i-python-container/blob/master/3.5/s2i/bin/run#L70

**Comment by jfmatth** [comment]
Ben, thanks again for the quick response.  

I'm glad to hear this.

Will i see you at Summit?

**Comment by bparees** [comment]
afraid not, but openshift will be well represented by other folks.
