### ISSUE TITLE
Detection of Django manage.py not predictable.

### ISSUE THREAD

**Issue by GrahamDumpleton** [sclorg/s2i-python-container#134]
The `assemble` script works out what is the Django `manage.py` file by using:

```
    # Find shallowest manage.py script, either ./manage.py or <project>/manage.py
    manage_file=$(find . -maxdepth 2 -type f -name 'manage.py' -printf '%d\t%P\n' | sort -nk1 | cut -f2 | head -1)
```

This is problematic when it could match multiple files because it takes the first in sorted order.

Someone could have `manage.py` in the root of their repository and then have a Django application directory called `hello`. They might for some reason create a file called `hello/manage.py` as part of their Django application code. The `find` command will pick up the `manage.py` in the sub directory rather than giving precedence to the `manage.py` in the root directory, because 'h' comes before 'm'.

The rule should be that if there is a `manage.py` in the root directory that it takes precedence.

If there is no `manage.py` in the root directory and you do resort to searching the immediate subdirectories, then it shouldn't blindly take the first one it finds as that still isn't predictable. It might initially use the right one, but then if someone later creates a new sub directory that comes earlier in sort order, then it will start using that new one when it shouldn't.

The rule should be that if more than one `manage.py` file is found when searching the immediate sub directories that it should issue a warning/error and then skip any attempt to interpret one as a Django `manage.py` file.

If for some reason a user really needs duplicates, but only one in a sub directory is the real `manage.py` file, then there would need to be an environment variable that can be set to say which it is.

Is arguable that only the `manage.py` in the root directory should be detected and if one in a sub directory is needed, then required that user specify environment variable indicating the location of the Django project by giving path to the `manage.py` in the sub directory.

There is also the issue mentioned in prior issues about `collectstatic` that there is no attempt to verify that the `manage.py` is actually for Django. The `Flask-Scripts` package also uses a `manage.py` and so could be incorrectly interpreted that is Django when it isn't.

**Comment by bparees** [comment]
i'd almost rather see us just look for it in root and if you want it somewhere else, we give you an env variable to tell us which manage.py file you want to use.  how does that sound?

**Comment by GrahamDumpleton** [comment]
Rather than environment variable giving path to manage.py in sub directory, my current thinking is that you give it the directory name for the Django project if not in root. The scripts would then look for manage.py within that directory itself rather than user calling it out explicitly. Thus instead of:

```
DJANGO_MANAGE_SCRIPT=hello/manage.py
```

would use:

```
DJANGO_PROJECT_NAME=hello
```

or similar.

**Comment by bparees** [comment]
DJANGO_PROJECT_DIR ?

**Comment by GrahamDumpleton** [comment]
To match Django's own name for the directory in ``settings.py``, probably should use ``DJANGO_BASE_DIR``. The ``settings.py`` file contains:

```
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
```

where ``BASE_DIR`` acts as the anchor point for any configuration to work out where stuff is inside of the project. The calculation should end up being the directory containing the ``manage.py`` so matches the directory we want to have be referenced. Thus should use same name stem.

**Comment by GrahamDumpleton** [comment]
Rather than making this Django specific, one could generalise it. In that case have generic ``APP_ROOT`` where the default currently is effectively ``/opt/app-root/src``. Setting it would mean that all checks would be done relative to the new directory. This way can also apply to checks for ``app.py`` and ``wsgi.py``.

I chose ``APP_ROOT`` here because other override variables are ``APP_FILE`` and ``APP_MODULE``, so carrying through ``APP_`` prefix. Using ``APP_ROOT`` may be confusing though when one considers that everything is under ``/opt/app-root``, yet ``APP_ROOT`` doesn't actually point to that by default, but the ``src`` subdirectory.

As far as overriding ``APP_ROOT``, the simple solution would be that it causes the current working directory to be changed to that directory before anything else is done. The one complication this presents is ``PYTHONPATH`` for Python module searches. The ``/opt/app-root/src`` directory would be in the module search path due to the fact that command line execution of Python results in special empty string in ``sys.path``, which means look in current working directory. Change the working directory and it will no longer look in ``/opt/app-root/src`` so if changing directory because ``APP_ROOT`` is set, then should add ``/opt/app-root/src`` to ``PYTHONPATH`` explicitly. There is actually good argument to add new directory specified by ``APP_ROOT`` to ``PYTHONPATH`` explicitly as well anyway. This will protect against badly written user code which changes the current working directory itself causing modules then not to be found.

**Comment by GrahamDumpleton** [comment]
Alternate name for variable may be ``APP_HOME``. Using ``HOME`` in name gives sense that the current working directory or home directory for the application will be changed.

**Comment by GrahamDumpleton** [comment]
Depending on where you change working directory may complicate working out name of WSGI module from ``setup.py`` as need to be in the top level directory to run ``setup.py``, you cannot run it from within a different directory as not really guaranteed to work. I think I have separately questioned whether is a good idea to use name of module installed by ``setup.py``. Better to make it explicit by requiring use supply a ``wsgi.py``.
