### ISSUE TITLE
Cherrypy - Running natively in OS3

### ISSUE THREAD

**Issue by jfmatth** [sclorg/s2i-python-container#147]
I have tried unsuccessfully to run CherrPy natively in OS3, as it's own server (i.e. no gunicorn or WSGI server).  

Any help is appreciated

app.py
```
import cherrypy

class Root(object):
    @cherrypy.expose
    def index(self):
        return "Hello World!"
if __name__ == '__main__':
    from cherrypy._cpnative_server import CPHTTPServer
    cherrypy.server.httpserver = CPHTTPServer(cherrypy.server)
    cherrypy.server.socket_host = "0.0.0.0"
    cherrypy.quickstart(Root(), '/')
```

requirements.txt
```
cherrypy
```

**Comment by bparees** [comment]
@grahamdumpleton any experience here?

**Comment by hhorak** [comment]
I think it will be caused by docker's handling sockets and cherrypy no happy about that way. Since when I exec into the container, it works:
```
# docker exec -ti `docker ps -q` bash
$> curl 127.0.0.1:8080
Hello World!
```

But on the host I also see:
```
curl: (56) Recv failure: Connection reset by peer
```

**Comment by hhorak** [comment]
Maybe this might help: https://groups.google.com/forum/#!topic/cherrypy-tickets/8T9oQKWjI_A

**Comment by GrahamDumpleton** [comment]
Example at:

* https://gitlab.com/osevg/python-cherrypy-engine

works fine.

It may be related to whatever:

```
    from cherrypy._cpnative_server import CPHTTPServer
    cherrypy.server.httpserver = CPHTTPServer(cherrypy.server)
```

is doing, which basic examples of using CherryPy do not use.

**Comment by jfmatth** [comment]
Ben, Graham and Honza,

Thank you for the quick response.  I'll check this out today.

John
