### ISSUE TITLE
pip version is too old and can't install Linux wheels

### ISSUE THREAD

**Issue by GrahamDumpleton** [sclorg/s2i-python-container#158]
You need at least pip version 8.1.0 in order to be able to install Linux wheels.

Some people (e.g. Sentry server), are now only making available some of their software packages as Linux wheels. This means it is impossible to install their software. This could get worse over time.

The SCL pip version should be updated.

There should also be an easy way for a user to say that a newer version of pip should be installed as part of the build before installing packages packages from requirements.txt. This will likely necessitate needing to add use of a Python virtual environment first, as you can't upgrade pip in a per user Python site-packages as it will fail trying to uninstall the system one first.

**Comment by pkubatrh** [comment]
Closing via #159
