### ISSUE TITLE
Should be using SCL httpd24 package and not operating system httpd packages.

### ISSUE THREAD

**Issue by GrahamDumpleton** [sclorg/s2i-python-container#161]
To make the S2I builder useful in a corporate setting where SSO is required, the SCL httpd24 package and associated authentication/authorisation modules for Apache should be installed rather than the operating system httpd package.

A need for SSO support via Apache httpd when using Python S2I has been raised on behalf of client in:

* https://bugzilla.redhat.com/show_bug.cgi?id=1393121

From other discussions also internal requirements for this.

Rather than installing:

```
httpd httpd-devel
```

should install:

```
httpd24 httpd24-httpd-devel httpd24-mod_ssl httpd24-mod_auth_kerb httpd24-mod_ldap httpd24-mod_session
```

In installing these, it is likely one doesn't need to remove:

```
centos-logos
```

or

```
redhat-logos
```

as they would not be installed by SCL versions of httpd packages.

As an additional SCL package is being installed, would need to update ``contrib/etc/scl_enable`` to use:

```
source scl_source enable httpd24 python27
```

rather than just:

```
source scl_source enable python27
```

Reference to Python package will be different for each Python version of builder image.

**Comment by GrahamDumpleton** [comment]
Actually, it seems like the ``centos-logos`` and ``redhat-logos`` are still being pulled in and so will need to still be removed. There is also a ``system-logos`` package being installed by ``httpd24-httpd`` package but don't know what that is for.

**Comment by torsava** [comment]
Closing the issue as #162 was merged.
