### ISSUE TITLE
Tests for each Python version should include mod_wsgi-express test.

### ISSUE THREAD

**Issue by GrahamDumpleton** [sclorg/s2i-python-container#163]
As mod_wsgi is one of the major WSGI servers, should include a test for mod_wsgi-express against each version.

**Comment by GrahamDumpleton** [comment]
This is dependent on #162.

**Comment by torsava** [comment]
Can this issue be closed since #162 was merged?

**Comment by GrahamDumpleton** [comment]
Yes, can be closed.
