### ISSUE TITLE
The project/__init__.py file should be removed from app-home-test-app test.

### ISSUE THREAD

**Issue by GrahamDumpleton** [sclorg/s2i-python-container#166]
The ``app-home-test-app`` test is for testing ``APP_HOME`` environment variable. The idea is that the specified directory then becomes the root from which the application source code is picked up. In using ``APP_HOME`` and for the purposes of the test, the ``project`` directory doesn't need to be a Python package itself. The ``project/__init__.py`` file should be removed as not needed.

**Comment by pkubatrh** [comment]
The way `APP_HOME` is implemented the current working directory is left unchanged and `project` is used by gunicorn as a package by running `gunicorn project.wsgi`, same as before. Hence the need for the `__init__.py` file. The only thing that really changed was that the `find` command only looks in the directory provided by `APP_HOME` (or the current working directory if unset) for the presence of `wsgi.py`

Is there any added value were we to change the working directory before executing an app instead?

**Comment by GrahamDumpleton** [comment]
If that is what it doing, that wasn't the intent of the original request for adding the feature. The intent was that it would change directory. If all it is doing is using ``project.wsgi``, then you could have just set ``APP_MODULE`` to ``project.wsgi`` and didn't need to add a new variable. It isn't particular useful in the current form and doesn't solve the reason for asking for it. Will check properly tomorrow then to see what was done. I never validated what it was doing.

**Comment by GrahamDumpleton** [comment]
Original comment where it was described what feature should do was https://github.com/sclorg/s2i-python-container/issues/134#issuecomment-235767928.

**Comment by pkubatrh** [comment]
>If that is what it doing, that wasn't the intent of the original request for adding the feature. The intent was that it would change directory. If all it is doing is using project.wsgi, then you could have just set APP_MODULE to project.wsgi and didn't need to add a new variable.

The new variable was needed for Django, as I would not call its `manage.py` a module (and point to it using `APP_MODULE`) and `APP_FILE` would be picked up as a regular python script. But you have a point that for gunicorn it would make more sense to just use `APP_MODULE`.

Also must have missed the mention of changing the cwd in the original issue - thanks for pointing me in the right direction. Will look into modifying the code to change the cwd for both Django and gunicorn (and modifying the tests).

**Comment by frenzymadness** [comment]
Is this issue still relevant? It seems that `APP_HOME` is used as an application home and working directory for years and there is no `__init__.py` file in `app-home-test-app/project` which this issue was created for.
