### ISSUE TITLE
Running arbitrary packaged app

### ISSUE THREAD

**Issue by t0ffel** [sclorg/s2i-python-container#176]
## Here is the use case I have:

I have a packaged python app. It has proper `setup.py`, so building is done automatically by s2i.
The python build produces executable, which I later want to simply launch with certain arguments(not a web app).

I don't see an easy way to do that with s2i. When running, the pod would crash, since it must execute the command and command is not there. Tried passing `APP_FILE`, but the result was that my executable is not found.

Remediation was to manually specify `command` and `args` in the deploymentconfig produced by s2i under `pod.podspec.container`.
That way `.s2i/run` is not executed, and my command gets executed properly.
Docker has analogue `--entrypoint` which allows specifying custom command to run in the image.

## The suggestion:

The suggestion is to add 2 new environmental variables: `APP_COMMAND` and `APP_ARGS`.
If they are present `.s2i/run` will execute `APP_COMMAND` with arguments `APP_ARGS`.

Please let me know what you think/whether there is an easier way to accomplish this.

//cc @aweiteka

**Comment by pkubatrh** [comment]
Thanks for the suggestion.
As far as I know there is currently no way to call an application with different arguments each time the image is run at this moment.
A part of this suggestion (the APP_COMMAND) is already being implemented via #174 which you will be able to use (once it is merged in) in case the arguments of the application do not change with each run of the image.

**Comment by pkubatrh** [comment]
You will also be able to set up a script (again via #174) in such a way that the script would expect arguments in an environment variable and then just pass it over to your command. This would allow you to use different arguments for the command with each run of the image.

**Comment by t0ffel** [comment]
@pkubatrh thanks. is it expected that after #174 you need to add `app.sh` script with the arguments embedded or you're open to having separate env var for arguments?

**Comment by pkubatrh** [comment]
@t0ffel Embedding the arguments was until now expected for every type of app currently, as we didn't hit a use case that needed something more yet.
However, given that `app.sh` can be a general shell script, you can just use you own environment variable to pass whatever you need to the script and use its contents as the arguments for the callable, as I pointed out in the last comment.

**Comment by GrahamDumpleton** [comment]
The ``app.sh`` change has now been merged. As that is deemed the solution believe this issue is okay to be closed.
