### ISSUE TITLE
Is /tmp/pip_default_default directory still used.

### ISSUE THREAD

**Issue by GrahamDumpleton** [sclorg/s2i-python-container#182]
The ``assemble`` scripts remove ``/tmp/pip_build_default`` but is that directory even created by anything now. Can't see any other mention of it, such as in an environment variable for ``pip``, so not sure why it would use it.

```
# remove pip temporary directory
rm -rf /tmp/pip_build_default
```

**Comment by torsava** [comment]
I did a little digging and I agree that it's not even created now. I suppose it can be removed.

**Comment by torsava** [comment]
Some more digging. It ceased to be created the moment we switched to using virtualenv.

I couldn't find anywhere where the `/tmp/pip_build_default` location was set, thus I suppose it was the default build dir location for pip of that version (though googling finds next to nothing).

Now the build directory is `/opt/app-root/build/` and it is removed automatically by pip.

∴ I think it should be safe to remove the line. I'll create a PR unless someone voices their opposition.
