### ISSUE TITLE
python 3.5.2+ support

### ISSUE THREAD

**Issue by erowan** [sclorg/s2i-python-container#183]
Hello,

Do you have plans to update the python version from 3.5.1?

**Comment by stratakis** [comment]
Hello.

For this request a new bug should be created at https://bugzilla.redhat.com for Red Hat Software Collections. The component is python and the version that you should choose there is rh-python35.

Currently there are no plans to update the rh-python35 collection to the newer interpreter yet, however having a feature request at the bugzilla will help on tracking it and evaluating for the next releases.

**Comment by dlbewley** [comment]
Not for 3.5, but using your tip @stratakis  I submitted a RFE for 3.6 https://bugzilla.redhat.com/show_bug.cgi?id=1490643

**Comment by torsava** [comment]
Hi @dlbewley, work on 3.6 is already under way here: #208.

**Comment by torsava** [comment]
Closing as version 3.6 is already available.
