### ISSUE TITLE
Build fails with TARGET=rhel7

### ISSUE THREAD

**Issue by torsava** [sclorg/s2i-python-container#187]
When I try to build the container on RHEL7.3 (in Vagrant) with `make build TARGET=rhel7` the build fails due to missing package `nss_wrapper`.
```
...
package nss_wrapper is not installed
The command '/bin/sh -c yum repolist > /dev/null &&     yum-config-manager --enable rhel-server-rhscl-7-rpms &&     yum-config-manager --enable rhel-7-server-optional-rpms &&     yum-config-manager --enable rhel-7-server-ose-3.2-rpms &&     yum-config-manager --disable epel >/dev/null || : &&     INSTALL_PKGS="python27 python27-python-devel python27-python-setuptools python27-python-pip     nss_wrapper httpd httpd-devel atlas-devel gcc-gfortran libffi-devel libtool-ltdl" &&     yum install -y --setopt=tsflags=nodocs $INSTALL_PKGS &&     rpm -V $INSTALL_PKGS &&     rpm -e --nodeps redhat-logos &&     yum clean all -y' returned a non-zero code: 1
make: *** [build] Error 1
```
I haven't been able to find a RHEL/RHSCL repository where `nss_wrapper` is located (if at all), though it is in [EPEL](https://admin.fedoraproject.org/pkgdb/package/rpms/nss_wrapper/).

**Comment by bparees** [comment]
We use some internal repos during the building of the rhel versions of these images which might be why you can't find it.  Do you have a particular need to build this yourself?

**Comment by torsava** [comment]
I see! I was just trying to test a pull request and was unable to build it.
