### ISSUE TITLE
Too many Gunicorn workers started by default on OpenShift

### ISSUE THREAD

**Issue by molund** [sclorg/s2i-python-container#188]
Our Python 3.5 pods have been allocated 1 core and 100 millicores of CPU resources.  By default, they are each starting 16 Gunicorn workers 

I think there may be a bug in the get_default_web_concurrency function.  

Based on line 27 in /3.5/s2i/bin/run, we shouldn't be getting more than 2 workers

```
local max=$((NUMBER_OF_CORES*2))
```

Here is the relevant output from ``oc describe pod mypodname``
```    QoS Tier:
      memory:	Guaranteed
      cpu:	Burstable
    Limits:
      memory:	512Mi
      cpu:	1
    Requests:
      cpu:		100m
      memory:		512Mi
```

As a work-around we can use a Gunicorn config file as described in the APP_CONFIG section here:
https://github.com/openshift/django-ex

**Comment by torsava** [comment]
In the meantime, you can also set the `WEB_CONCURRENCY` environment variable in your `.s2i/environment` file as described [here](https://github.com/sclorg/s2i-python-container/blob/master/3.5/README.md#environment-variables).

**Comment by bkabrda** [comment]
@molund if you still have some of these pods around, could you please try `oc exec mypodname cat /sys/fs/cgroup/cpuset/cpuset.cpu` and post the output of that? It would really help with debugging this issue. Thanks!

**Comment by frenzymadness** [comment]
Is this issue still relevant? There are multiple ways how you can affect the number of workers.

**Comment by frenzymadness** [comment]
We have insufficient data to resolve this. If it still affects you, please reopen.
