### ISSUE TITLE
No way to not run app.py if it exists

### ISSUE THREAD

**Issue by aule** [sclorg/s2i-python-container#190]
When trying to run a simple flask app through gunicorn, I encountered unusual behaviour where my app was running on the flask development server instead of following anything in the wsgi.py file. It was caused because I had unimaginatively called my app "app.py". I couldn't find any way to avoid this behaviour other than to rename the file to "flaskapp.py" instead.

This seems to be a side-effect of resolving https://github.com/sclorg/s2i-python-container/issues/56 which rules out the simplest solution of reversing the order. Bearing this in mind, I do not know if there even is an ideal solution without giving up on the automagic XKCD1654 style approach.

The code added by https://github.com/sclorg/s2i-python-container/issues/86 unfortunately removes the workaround of setting the $APP_FILE to something nonexistent.

**Comment by torsava** [comment]
I opened a pull request that should fix this issue by allowing you to set `APP_FILE` to a null value that will *not* be overwritten to `app.py`. Could you please test it?

**Comment by aule** [comment]
I've tested the following:
* Without the fix, my application runs on the development server (app.py)
* After the fix but without any environment changes, my application still runs on the development server
* After the fix and adding an empty APP_FILE environment variable, my application runs as desired on gunicorn

All working well, thanks.
