### ISSUE TITLE
Automatic determination of gunicorn processes when no resource limits.

### ISSUE THREAD

**Issue by GrahamDumpleton** [sclorg/s2i-python-container#199]
Saw this behaviour sometime back but possibly forgot to raise it. I can't revalidate it right now, but should be investigated to see if still an issue.

The issue is that if there are no resource limits set on a deployment, nor enforced on it by being set on a project and inherited, then it appears the whole amount of resources available to the node is used in the calculation of the number of process to run gunicorn with.

The consequence of this is that if the node had 100+ GB of memory, then a ridiculous number of gunicorn processes get allocated, way more than is reasonable. If there are no limits set on the deployment configuration, the amount of processes gunicorn is configured to use should be capped at some reasonable level.

This almost caused issues when using a single node cluster with lots of memory in some training, as the gunicorn example unexpectedly consumed huge amounts of memory. Luckily not everyone doing the training did the deployment because if they did, it would have overwhelmed the node.

**Comment by bkabrda** [comment]
According to gunicorn docs [1]: "Gunicorn should only need 4-12 worker processes to handle hundreds or thousands of requests per second." - Therefore I'd like to propose that we use 12 as maximum number of worker processes (while allowing users to override). I'll send a PR that implements this today.

[1] http://docs.gunicorn.org/en/stable/design.html#how-many-workers
