### ISSUE TITLE
UPGRADE_PIP_TO_LATEST should also perhaps update wheel package as well.

### ISSUE THREAD

**Issue by GrahamDumpleton** [sclorg/s2i-python-container#201]
``UPGRADE_PIP_TO_LATEST`` environment variable when set will update to latest version of ``pip``, but it should also perhaps update to latest version of ``wheel`` at the same time. If you don't you can hit problems when doing stuff with wheels still, such as:

* https://bitbucket.org/pypa/wheel/issues/146/wheel-building-fails-on-cpython-350b3

In short, these packages should really be upgraded together to ensure newest packaging tools are being used.

**Comment by GrahamDumpleton** [comment]
Also should pull in latest ``setuptools`` to be safe.

**Comment by torsava** [comment]
Agreed, pip, setuptools and wheel are highly interconnected and we should update all three.
