### ISSUE TITLE
Oracle libraries require libaio.

### ISSUE THREAD

**Issue by GrahamDumpleton** [sclorg/s2i-python-container#205]
The Linux async io library libaio is not part of the image which means that if someone installs Oracle client libraries themselves as part of a custom ``assemble`` wrapper script in order to install ``cx_Oracle`` Python client package, then it all fails.

* https://stackoverflow.com/questions/45180023/wget-curl-binaries-onto-openshift-before-dependencies-installation

The common base image should perhaps be updated to install libaio as there shouldn't be any impediment for using client libraries for any of the major database products, even if the user has to install the database libraries themselves as is case for Oracle.

**Comment by torsava** [comment]
Moved the issue to the [sclorg/s2i-base-container](https://github.com/sclorg/s2i-base-container) repo.
