### ISSUE TITLE
Permissions on /opt/app-root set wrong in 3.5 image.

### ISSUE THREAD

**Issue by GrahamDumpleton** [sclorg/s2i-python-container#210]
In 2.7, 3.3 and 3.4, the ``Dockerfile`` and ``Dockerfile.RHEL`` did:

```
# In order to drop the root user, we have to make some directories world
# writable as OpenShift default security model is to run the container under
# random UID.
RUN chown -R 1001:0 /opt/app-root && chmod -R ug+rwx /opt/app-root
```

For whatever reason this was changed in 3.5 image to:

```
# In order to drop the root user, we have to make some directories world
# writable as OpenShift default security model is to run the container under
# random UID.
RUN chown -R 1001:0 /opt/app-root && chmod -R og+rwx /opt/app-root
```

That is, it now does ``chmod -R og+rwx`` instead of ``chmod -R ug+rwx``.

There is no good reason that have ever seen that others (instead of user), should be given write permission.

This is also likely now better done as:

```
RUN chown -R 1001:0 /opt/app-root && fix-permissions /opt/app-root
```

since ``fix-permissions`` now seems to better encapsulate best practice for what permissions should be set to, also ensuring that permissions aren't changed when not needed, so as to ensure don't create extra copies of files in a new layer.

The only issue would be whether the original ``u+rwx`` did anything, but since it was changed to ``o+rwx`` and been no complaints that have seen, probably not, meaning that what ``fix-permissions`` does it more correct.

Note that this possibly wrong change is also being propagated in #208 for 3.6 images.

This ``RUN`` command is also better off being merged into the prior step of:

```
# Create a Python virtual environment for use by any application to avoid
# potential conflicts with Python packages preinstalled in the main Python
# installation.
RUN source scl_source enable rh-python35 && \
    virtualenv /opt/app-root
```

Which ever method is used to fix permissions, because it is separate ``RUN`` command, it is going to create copies of files created when ``virtualenv`` was run.

**Comment by torsava** [comment]
I agree with the proposed changes, especially changing the ownership and permissions in the same instructions the directory gets created in. I've proposed it as a PR #212.

**Comment by mcyprian** [comment]
#212 was merged, so I am closing this.
