### ISSUE TITLE
common/build.sh: line 34: syntax error near unexpected token `;;'

### ISSUE THREAD

**Issue by evilbinary** [sclorg/s2i-python-container#220]
on mac osx 10.12.6 
$make build TARGET=centos7 VERSIONS=2.7

VERSION="2.7" SKIP_SQUASH=1 UPDATE_BASE= OS=centos7 CLEAN_AFTER= DOCKER_BUILD_CONTEXT=. OPENSHIFT_NAMESPACES="3.3" common/build.sh
common/build.sh: line 34: syntax error near unexpected token `;;'
make[1]: *** [2.7] Error 2

**Comment by omron93** [comment]
@evilbinary Thanks for reporting this. We are using shared build scripts for all sclorg/ images and this seems as failure in these scripts. So moving to https://github.com/sclorg/container-common-scripts/issues/35

**Comment by torsava** [comment]
The issue has been fixed in the container-common-scripts and so I'm closing it!
