### ISSUE TITLE
undefined symbol: _PyErr_ReplaceException error

### ISSUE THREAD

**Issue by h4rr21** [sclorg/s2i-python-container#226]
may be related with:
[https://github.com/SynoCommunity/spksrc/issues/1753](url)

trying to install requirements.txt 

cat requirements.txt                                                                      
flask
flask-bootstrap

docker build -t raspi:web .                                                             
Sending build context to Docker daemon  6.885MB
Step 1/7 : FROM centos/python-27-centos7
 ---> 6dc17c3695d0
Step 2/7 : ENV INITSYSTEM on
 ---> Running in 1c8f9cb8c7f1
 ---> 9a31926b6945
Removing intermediate container 1c8f9cb8c7f1
Step 3/7 : WORKDIR /usr/src/app
 ---> ef14201235df
Removing intermediate container 54aa3e982f9c
Step 4/7 : COPY . /usr/src/app
 ---> 2c9dfcd8a584
Step 5/7 : RUN pip install -r requirements.txt
 ---> Running in 498fa2751426
Traceback (most recent call last):
  File "/opt/app-root/bin/pip", line 7, in <module>
    from pip import main
  File "/opt/app-root/lib/python2.7/site-packages/pip/__init__.py", line 13, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/opt/app-root/lib/python2.7/site-packages/pip/utils/__init__.py", line 15, in <module>
    import zipfile
  File "/opt/rh/python27/root/usr/lib64/python2.7/zipfile.py", line 6, in <module>
    import io
  File "/opt/rh/python27/root/usr/lib64/python2.7/io.py", line 51, in <module>
    import _io
ImportError: /opt/app-root/lib64/python2.7/lib-dynload/_io.so: undefined symbol: _PyErr_ReplaceException

**Comment by mcyprian** [comment]
Thanks for reporting this @h4rr21. The problem here is that `LD_LIBRARY_PATH` environment variable is empty during docker build. The workaround is to add `ENV LD_LIBRARY_PATH=/opt/rh/python27/root/usr/lib64` to your Dockerfile.

We could maybe add some definition of `LD_LIBRARY_PATH` to `centos/python-27-centos7`itself (and other s2i images) for similar cases, what is your opinion on this @hhorak @torsava @GrahamDumpleton @omron93?

**Comment by GrahamDumpleton** [comment]
You can't set just ``LD_LIBRARY_PATH`` manually as technically other environment variables may need to be set or actions run. You need to use:

```
RUN . /opt/app-root/etc/scl_enable && pip install -r requirements.txt
```

I would ask though why you are doing ``pip`` installs from a derived image ``Dockerfile`` anyway given that this is what the S2I process is intended for. It is probably better to emulate the steps that source code injection does and then trigger the ``assemble`` script from the S2I builder. For example:

* https://github.com/openshift-katacoda/blog-django-py/blob/master/Dockerfile

No need to do ``scl_enable`` in that case is it happens as a side effect of running the ``assemble`` shell script.

That ``Dockerfile`` example allows me to do a normal ``docker build`` yet get the capabilities of S2I. I can have Docker Hub do it for an automated build and so effectively get the same outcome as S2I but without ``s2i``.

Just note that that example is using custom ``.s2i/bin`` scripts, so if not using overrides, you would execute those under ``/usr/libexec/s2i``.

Also, would strongly recommend you still use the S2I blessed directory of ``/opt/app-root/src`` for things and not ``/usr/src/app``.

**Comment by omron93** [comment]
Please take a look in https://github.com/sclorg/s2i-base-container/pull/147 which should solve this problem.

**Comment by omron93** [comment]
Unfortunately we have to revert https://github.com/sclorg/s2i-base-container/pull/147

For more information see https://github.com/sclorg/s2i-base-container/issues/150 and upstream bug report https://github.com/moby/moby/issues/35832 .

So I'm reopening this issue. I hope upstream moby will resolve the issue.

**Comment by frenzymadness** [comment]
Is this issue still relevant or did you manage to use our base image without manual installation of dependencies?

**Comment by GrahamDumpleton** [comment]
The solution is to use ``scl_enable``. It is the only reliable way of ensuring the SCL Python is setup properly when running commands in ``Dockerfile``. Believe this can be closed.

**Comment by frenzymadness** [comment]
Closing then.
