### ISSUE TITLE
Python 3.6 S2I builder will not work with Django.

### ISSUE THREAD

**Issue by GrahamDumpleton** [sclorg/s2i-python-container#237]
Logging this here as an FYI for when people trying to use Python 3.6 S2I builder with Django find it doesn't work.

In short, you can't create a Django super user account with ``python manage.py createsuperuser`` as the SCL Python 3.6 hashlib implementation breaks usage of hashlib.

The error you will see when running creating super user is:

```
TypeError: object supporting the buffer API required
```

This will need to be chased up through SCL team who manage Python distros.

Only workaround is to avoid Python 3.6 S2I builder and use that for Python 3.5 instead.

The script below distils it down to simple test to replicate it.

```
# bug.py

import hashlib

class Test:
   digest = hashlib.sha256

   def check(self):
       print(self.digest)

   def name(self):
       print(self.digest().name)

t = Test()

t.check()
t.name()


# MacOS (CPython binaries from PSF)

$ python3.5 bug.py
<built-in function openssl_sha256>
sha256

$ python3.6 bug.py
<built-in function openssl_sha256>
sha256

# CentOS (CPython compiled from source code from PSF)

$ python3.5 bug.py
<built-in function openssl_sha256>
sha256

$ python3.6 bug.py
<built-in function openssl_sha256>
sha256

# CentOS (CPython binaries from Software Collections Library)

$ python3.5 bug.py
<built-in function openssl_sha256>
sha256

$ python3.6 bug.py
<bound method openssl_sha256 of <__main__.Test object at 0x7f437c2616a0>>
Traceback (most recent call last):
 File "bug.py", line 15, in <module>
   t.name()
 File "bug.py", line 10, in name
   print(self.digest().name)
 File "/opt/app-root/lib64/python3.6/hashlib.py", line 90, in inner
   return func(*args, **kwargs)
TypeError: object supporting the buffer API required
```

**Comment by hhorak** [comment]
cross-linking: https://bugzilla.redhat.com/show_bug.cgi?id=1528775

**Comment by stratakis** [comment]
cross-linking also: https://bugzilla.redhat.com/show_bug.cgi?id=1497342

**Comment by mcyprian** [comment]
This was already fixed for CentOS 7 according to the discussion in bug https://bugzilla.redhat.com/show_bug.cgi?id=1497342. I also tried to reproduce this in the latest python-36-centos7 image. Everything seems to work fine now.
