### ISSUE TITLE
Templates should live with example app

### ISSUE THREAD

**Issue by pvalena** [sclorg/s2i-python-container#239]
See https://github.com/openshift/rails-ex/issues/105.

**Comment by frenzymadness** [comment]
Sorry, but I don't understand this issue. I cannot find any openshift templates in this repository. Could you please provide more details? Sorry if I am missing something obvious.

**Comment by torsava** [comment]
@pvalena Is this still relevant?

The templates we have (`django-postgresql-persistent.json` and `django-postgresql.json`) reside directly in the `example` directory.

**Comment by frenzymadness** [comment]
This issue is more than two months without reply so I am closing it. Feel free to reopen it if you still need any help from us.
