### ISSUE TITLE
Use openshift/django-ex for openshift tests

### ISSUE THREAD

**Issue by omron93** [sclorg/s2i-python-container#240]
Fix TODO (https://github.com/sclorg/s2i-python-container/blob/master/test/run-openshift#L25) introduced in https://github.com/sclorg/s2i-python-container/pull/238 :

```
# TODO: update the template reference to proper location, 
once https://github.com/openshift/django-ex/pull/115 is merged
```

To use openshift/django-ex repo instead of hhorak/django-ex fork.

**Comment by frenzymadness** [comment]
Fixed in https://github.com/sclorg/s2i-python-container/commit/f7b340c25b0c3ceaef2d08c958d609be6045270d
