### ISSUE TITLE
Move virtualenv from APP_ROOT to specific path

### ISSUE THREAD

**Issue by mcyprian** [sclorg/s2i-python-container#243]
A virtual environment is currently [created under APP_ROOT directory ](https://github.com/sclorg/s2i-python-container/blob/master/3.6/Dockerfile#L61). I don't like this design decision very much. In my opion it would be much nicer and cleaner to have virtual environment at the specific path, reserved for this purpose. 
Majority of higher level tools in Python world store virtual environments in locations like:
```
~/.local/venvs (pipsi)
~/.virtualenvs/ (virtualenvwrapper)
~/.local/share/virtualenvs/ (pew)
```
For python container something like $APP_ROOT/.virtualenv/ might work. As far as I know similar change shouldn't cause any backwards incompatibility issues.

**Comment by GrahamDumpleton** [comment]
FWIW, it was partly created where it was since ``/opt/app-root/bin`` is already in the default ``$PATH``. You are going to have issue with ensuring the virtual environment ``bin`` directory is in ``$PATH`` if you allow which directory is used to be customised by a user.

**Comment by GrahamDumpleton** [comment]
You also can't put it under ``~/``, as ``$HOME`` is ``/opt/app-root/src``, which is where app code goes. Having it under there can cause conflicts with user code incorporated using S2I build process, or could cause exposure of files from the virtual environment if ``/opt/app-root/src`` is used a root directory for files exposed by a web server. Having it under ``$HOME`` also prevents tricks of where when using ``oc cluster up`` you mount ``hostDir`` volume from local host as ``/opt/app-root/src`` and run stuff from local host. If the virtual environment was under ``$HOME``, it would be hidden when this was done. It can actually be argued that have ``$HOME`` as ``/opt/app-root/src`` was a bad decision and ``/opt/app-root`` would have been better.

**Comment by frenzymadness** [comment]
It seems to me that this enhancement may cause more troubles and incompatibilities than it solves problems (if any). Does it worth to keep it open and think about possible solutions further?

**Comment by GrahamDumpleton** [comment]
No one has ever reported a specific problem with how things are done that I know of, so issue is one of opinion only of how to do it. Too much would be dependent on current layout and changing it would most definitely break things. Believe it should be closed.

**Comment by frenzymadness** [comment]
Thank you for your opinion. Closing.
