### ISSUE TITLE
Image centos/python-35 broken

### ISSUE THREAD

**Issue by vpavlin** [sclorg/s2i-python-container#246]
I see following error since the latest rebuild of the image (https://hub.docker.com/r/centos/python-35-centos7/tags/):

```
error while loading shared libraries: libpython3.5m.so.rh-python35-1.0: cannot open shared object file: No such file or directory
```

Could it be due to permission changes @mcyprian pushed 2 days ago?

I am trying to build and run https://github.com/jupyter-on-openshift/jupyterhub-quickstart and the container fails to start with the error above.

Change to 3.6 gets me over this error, but brings different issues

**Comment by hhorak** [comment]
Cannot reproduce just with pure s2i:
`s2i build https://github.com/jupyter-on-openshift/jupyterhub-quickstart  centos/python-35-centos7 testjup ; docker run -ti --rm testjup`

**Comment by GrahamDumpleton** [comment]
I am also not seeing an issue when using Python 3.6 image.

**Comment by mcyprian** [comment]
@GrahamDumpleton -L flag was replaced by -R when running fix-permissions script under root user. This was done to prevent [undesirable permission changes of software collection files](https://bugzilla.redhat.com/show_bug.cgi?id=1536129).
    base-container https://github.com/sclorg/s2i-base-container/pull/154
    python-container https://github.com/sclorg/s2i-python-container/pull/245

**Comment by vpavlin** [comment]
Hi, sorry for this panic thing - I got sloppy and mounted a file over `/opt/app-root/etc/` which, obviously broke everything. I only noticed this after more debugging. Sorry again, closing

**Comment by navidshaikh** [comment]
@hhorak  @mcyprian @GrahamDumpleton :  I am seeing this with python-35 image, am I missing something?

```
# cat Dockerfile.2 
FROM registry.centos.org/centos/python-35-centos7:latest

RUN echo "connextion" > /tmp/requirements.txt

RUN pip3 install --no-cache-dir -r /tmp/requirements.txt

ENTRYPOINT ["python3"]

# docker build -t test_python35 -f Dockerfile.2 .
Sending build context to Docker daemon 257.5 kB
Step 1/4 : FROM registry.centos.org/centos/python-35-centos7:latest
 ---> 04f31f542db0
Step 2/4 : RUN echo "connextion" > /tmp/requirements.txt
 ---> Using cache
 ---> d45b803b7576
Step 3/4 : RUN pip3 install --no-cache-dir -r /tmp/requirements.txt
 ---> Running in 749d8a8b0e37

/opt/app-root/bin/python3: error while loading shared libraries: libpython3.5m.so.rh-python35-1.0: cannot open shared object file: No such file or directory
The command '/bin/sh -c pip3 install --no-cache-dir -r /tmp/requirements.txt' returned a non-zero code: 127
```

**Comment by navidshaikh** [comment]
@pkubatrh 

I'm trying to install an app requirements via pip3.

What's the recommended way to use `pip3` or install requirements in centos/python-35-centos7:latest
 container ?

**Comment by pkubatrh** [comment]
@navidshaikh Either through the Dockerfile, as you are already doing, or via source-to-image (s2i). 

You might want to have a look at the documentation for [s2i](https://github.com/openshift/source-to-image) and for [the python image](https://github.com/sclorg/s2i-python-container/blob/master/3.5/README.md) if you have troubles using either. There are also some example applications in https://github.com/sclorg/s2i-python-container/tree/master/examples that might be useful for you.

**Comment by GrahamDumpleton** [comment]
You want to use something like:

```
RUN source scl_source enable rh-python35 && \
          pip3 install --no-cache-dir -r /tmp/requirements.txt
```

Invoking bash sub shell to run it may not work depending on how base image is set up.
