### ISSUE TITLE
Run tests of Fedora Dockerfiles in CI

### ISSUE THREAD

**Issue by mcyprian** [sclorg/s2i-python-container#266]
Tests of Fedora Dockerfile are missing in the CI. We already have this Dockerfile in the repo for some time, it would be nice to test it as well.

**Comment by omron93** [comment]
@mcyprian Are you fine with testing only "basic" tests? (not the openshift one)

**Comment by mcyprian** [comment]
It is definitely better than no tests at all.

**Comment by omron93** [comment]
Fedora CI is enable now. It is triggered in same way as CentOS and RHEL CI ([test] or commit from sclorg/ member)

**Comment by mcyprian** [comment]
Great, thanks for that @omron93.
