### ISSUE TITLE
Including RPM Python binding in the container

### ISSUE THREAD

**Issue by junaruga** [sclorg/s2i-python-container#268]
There is a request from @goern that he wants to use RPM Python binding (`import rpm`) in the Python SCL container.
https://github.com/junaruga/rpm-py-installer/issues/76

I would forward it here.

## Possible solutions

1. Run `pip install rpm-py-installer` in the `Dockerfile` when `docker build`.
2. Create python-rpm SRPM including `python3-rpm`, and add it to the Python SCL package list.
   Right now `python3-rpm` is defined in rpm.spec.
   https://src.fedoraproject.org/rpms/rpm/blob/master/f/rpm.spec

**Comment by GrahamDumpleton** [comment]
You could only install the system package and would have to explicitly use the system python at ``/usr/bin/python``. You would have to ignore the SCL Python.

Is not obvious what the use case is for this.

**Comment by frenzymadness** [comment]
Is this issue still relevant? @goern What do you think about the first possible solution mentioned above?

**Comment by torsava** [comment]
@junaruga If the user wants the `rpm-py-installer` package installed by pip, they can add it to their `requirements.txt` (or similar) and it will get installed. Or is there some problem with this approach?

**Comment by junaruga** [comment]
@torsava Yes, they can install it by `requirements.txt`. The use case is considered.

**Comment by torsava** [comment]
@junaruga In that case there's no change necessary in the s2i-python-container, right? If you agree, let's close this issue.

**Comment by junaruga** [comment]
@torsava yes I think no change necessary for that.
There is the RPM package on SUSE.
https://build.opensuse.org/package/show/home:jayvdb:rpm/python-rpm-py-installer
But I do not think that we need the RPM package in the container use case.
