### ISSUE TITLE
what is dg?

### ISSUE THREAD

**Issue by alfonsomhc** [sclorg/s2i-python-container#274]
I'm following the installation instructions. When I run:
`make build TARGET=rhel7 VERSIONS=3.6`
I get:
```
$ make build TARGET=rhel7 VERSIONS=3.6
MANIFEST_FILE="manifest.sh" \
VERSIONS="3.6" \
DG="/bin/dg" /usr/bin/env bash common/generate.sh
common/generate.sh: line 26: /bin/dg: No such file or directory
FATAL: version not found
make[1]: Entering directory `/test/s2i-python-container'
  DG     3.6/README.md
bash: line 1: /bin/dg: No such file or directory
make[1]: *** [3.6/README.md] Error 127
make[1]: Leaving directory `/test/s2i-python-container'
make: *** [build-serial] Error 2
```
I have been looking in your repo and googling, but I'm not sure where to get the dg package...

**Comment by alfonsomhc** [comment]
I suspect it is this:
https://github.com/devexp-db/distgen/

**Comment by pkubatrh** [comment]
>I suspect it is this: https://github.com/devexp-db/distgen/

That is correct. Distgen is used in this repository to generate versioned image sources from templates. 

I have created a PR for common scripts that modifies the generate script so that a proper error message is written out in case the distgen binary is not available on the machine.

**Comment by alfonsomhc** [comment]
Thank you!
