### ISSUE TITLE
Python 3.5.1 is too old. Latest in 3.5 series is 3.5.5.

### ISSUE THREAD

**Issue by GrahamDumpleton** [sclorg/s2i-python-container#276]
Use of 3.5.1 will potentially cause issues with any complex asyncio code as there were various important bug fixes/changes in asyncio in 3.5.2.

Example of sort of error you might see in 3.5.1.

```
File "/opt/app-root/lib/python3.5/site-packages/async_generator/_util.py", line 14, in __aexit__
  | await self._aiter.aclose()
  | AttributeError: 'coroutine' object has no attribute 'aclose'
```

I know the version will not be updated, so logging this more for documentation. Users should use 3.6 instead.

**Comment by frenzymadness** [comment]
I think that we can close this now. Python 3.7 is released which makes version 3.5 even more obsolete (released in source code form only) and also epel7 is switching its default Python from 3.4 to 3.6. IMHO all developers using 3.5 should be aware of the lack of functionality.

Feel free to reopen it if you think that it's necessary to keep it here.
