### ISSUE TITLE
Environment variable ENV is not set?

### ISSUE THREAD

**Issue by HolySamosa** [sclorg/s2i-python-container#277]
I've tried the environment variable `ENV` both in my `.s2i/environment` file and directly via OpenShift's environment configuration, but in both cases `ENV` is not set in my application pod when my Flask 12.2 app is created.

Thanks for your advice.

**Comment by pkubatrh** [comment]
Likely due to:
https://github.com/sclorg/s2i-python-container/blob/master/src/root/opt/app-root/etc/scl_enable#L4

**Comment by HolySamosa** [comment]
Thanks, @pkubatrh .  

I'm now using `FLASK_ENV` instead to set my production / development environment, so we can close this issue.
