### ISSUE TITLE
Bundled node version doesn't work for HTTPS servers.

### ISSUE THREAD

**Issue by GrahamDumpleton** [sclorg/s2i-python-container#282]
If try and use the bundled node version to run:

```
var https = require("https");
var fs = require("fs");

var options = {
  key: fs.readFileSync("tls.key"),
  cert: fs.readFileSync("tls.crt")
};

var port = 8443;

function handleRequest(req, res) {
  //Process Post Request
  res.write(req.url);
}

//Create a server
var server = https.createServer(options, handleRequest);

//Start server
server.listen(port, function() {
  console.log("Server listening on: https://localhost:" + port);
});
```

where ``tls.key`` and ``tls.crt`` were added by using a service signing certificate, the node process will either crash, or will hang up the connection immediately without returning any data.

There thus seems to be something wrong with SSL support in the old node version being used.

Perhaps should look at updating to node 8 instead of node 6.

**Comment by omron93** [comment]
> Perhaps should look at updating to node 8 instead of node 6.

rh-nodejs8 is now used in python images. Merge in s2i-base image in https://github.com/sclorg/s2i-base-container/pull/170.

**Comment by frenzymadness** [comment]
I can confirm that Python images now use node v8. Did this update solve your problem?

**Comment by GrahamDumpleton** [comment]
I will need to test whether newer version does fix the issue and report back.

**Comment by GrahamDumpleton** [comment]
And now the base image uses NodeJS 10, which caused me issues with a project because something which was being used only worked up to NodeJS 8. These jumps in NodeJS version in base image could cause problems and because the CentOS images aren't tagged, it is impossible to fix usage to an older image with older NodeJS version. Luckily I was using base image using docker build and so could install the NodeJS 8 version in parallel to NodeJS 10 for now. Suspect this could cause issues for others though.

Anyway, still not verified whether the HTTPS server crash issue is fixed.

**Comment by pkubatrh** [comment]
We updated to nodejs-10 in base early since nodejs-8 will hit EOL soon. Afaik @torsava is already working on a solution to having CentOS images tagged on Dockerhub for each build so that users have a fallback available when something breaks.

@hhorak FYI ^ maybe we could increment the version of the s2i-base image on nodejs update since it seems to be a breaking change for some applications?

**Comment by frenzymadness** [comment]
Yes, we are aware that image tagging would be very useful. Issue https://github.com/sclorg/s2i-python-container/issues/301

**Comment by hhorak** [comment]
I think the main problem we see here is that the nodejs included in the s2i-base is used as not meant to be used. The reason to include the NPM was to allow installing JS libraries easily, it is also mentioned in the README:

```
This container image includes an npm utility, so users can use it to install JavaScript modules for their web applications. There is no guarantee for any specific npm or nodejs version, that is included in the image; those versions can be changed anytime and the nodejs itself is included just to make the npm work.
```

Going from one version of nodejs to another might of course change behaviour, we won't be able to do much about this, so I tend to say that if somebody needs to use the Node.js more than just for running `npm install`, then they should either accept this risk of changing versions, or create own image with an exact Node.js stream.

**Comment by hhorak** [comment]
> @hhorak FYI ^ maybe we could increment the version of the s2i-base image on nodejs update since it seems to be a breaking change for some applications?

This would cause issues for all who use s2i-base directly (they might not change the version and would use not-updated image without knowing) and would not help users of all the depended images like python, where we'd change the FROM silently. So, I don't see much of a benefit here.

**Comment by hhorak** [comment]
@GrahamDumpleton, may I know why you run nodejs in the python image at all? What is the practical use of this?

**Comment by GrahamDumpleton** [comment]
My specific use case isn't normal, but it is quite normal for people when using a derived Python S2I container to use ``npm`` to install Javascript packages for frontend development. Even if they pin Javascript package versions, things can break when the ``npm`` version is changed, because Javascript packages can often include explicit checks of the ``npm`` version and will fail if you aren't using the correct ``npm`` version that the package wants.

**Comment by hhorak** [comment]
> Javascript packages can often include explicit checks of the `npm` version and will fail to install if you aren't using the correct `npm` version that the package wants.

Hm, that's not really nice. Fortunately, we don't see many issues like that, and hopefully such incompatibility issues like this are fixed upstream soon enough to not cause real troubles. In any case, since Node.js community is very agile, staying with the latest Node.js version is probably what can help here, as I expect that the incompatibility issues happen mostly with older versions.

**Comment by GrahamDumpleton** [comment]
Closing this issue as original issue with HTTPS server crashing with node 6 seems to be fixed with node 10.
