### ISSUE TITLE
pass extra arguments to pipenv

### ISSUE THREAD

**Issue by goern** [sclorg/s2i-python-container#283]
As a S2I User, I would like to pass extra arguments to pipenv, so that its execution could be verbose or so that its execution could include dev dependencies.

**Comment by fridex** [comment]
Changes proposed to pipenv - https://github.com/pypa/pipenv/pull/2537

**Comment by fridex** [comment]
Just an update - PEEP standard was accepted that will provide such functionality in https://github.com/pypa/pipenv/blob/master/peeps/PEEP-002.md

**Comment by frenzymadness** [comment]
Update: [Original PR](https://github.com/pypa/pipenv/pull/2537) is closed but the [PEEP](https://github.com/pypa/pipenv/blob/master/peeps/PEEP-002.md) is accepted and a [new PR](https://github.com/pypa/pipenv/pull/2819) is merged and I can find it in [changelog](https://github.com/pypa/pipenv/releases/tag/v2018.11.14).

So I tested it with simple `s2i build` command where I used `-e` to pass some `PIPENV_` variable to build and it works.

From my point of view we are done here so I am closing this issue. If I am wrong and you need anything else, feel free to open it.
