### ISSUE TITLE
Add Python 3.7 support

### ISSUE THREAD

**Issue by commandtab** [sclorg/s2i-python-container#284]
I'm not sure if there are upstream dependencies I'm not aware of, but I'd like to have Python 3.7 support added.

Thanks for the great project! I depend on this every day, and have found it to be very reliable and quite flexible. In particular, the `pipenv` support was an excellent addition  👍

**Comment by pkubatrh** [comment]
Hi, thanks for opening up an issue for this!

The dependency for adding CentOS and RHEL based images to this repository is to have Python 3.7 packaged in those distributions. AFAIK this is not the case for either right now and we cannot promise any ETA.

I will keep this issue open so that the addition of the 3.7 version can be properly tracked.

**Comment by sub-mod** [comment]
Is there an update on this ?
I can't find centos/python-37-centos7 image but it is mentioned in the 3.7 docs.

**Comment by pkubatrh** [comment]
Hi @sub-mod 

Python 3.7 has been added for Fedora in https://github.com/sclorg/s2i-python-container/pull/316. Unfortunately the docs mistakenly mention that CentOS7/RHEL7/RHEL8 based images also exist, which is not the case. See https://github.com/sclorg/s2i-python-container/issues/314

**Comment by frenzymadness** [comment]
Just a note that the Python 3.7 probably won't be available for Centos/RHEL in foreseeable future so if you really need this Python version, use Fedora image where 3.7 is the default Python in Fedora 29.

**Comment by commandtab** [comment]
@frenzymadness What makes you say that?

**Comment by frenzymadness** [comment]
@commandtab It's just my opinion based on the fact that epel7 is currently switching from Python 3.4 to 3.6 and Python 3.6 is the main one in RHEL8 so unless there will be a request for 3.7 we'll maintain version 3.6.

**Comment by sub-mod** [comment]
@frenzymadness any news on devtoolset with python3.7 ?

**Comment by frenzymadness** [comment]
@sub-mod I don't know much about devtoolset containers (I am new here) but it seems that it should be possible to update 7-toolchain container from Fedora 27 to Fedora 29 which would mean switch to Python 3.7.

Could you please open an issue there and ping me in it?

**Comment by frenzymadness** [comment]
Python 3.7 is available in Fedora 29 so I am closing this issue.
