### ISSUE TITLE
generate_container_user can not create `/opt/app-root/etc/passwd`

### ISSUE THREAD

**Issue by goern** [sclorg/s2i-python-container#298]
at https://github.com/sclorg/s2i-python-container/blob/9e911631f49ca5de59260c882c0b6ff5c5ad3ee8/3.6/root/opt/app-root/etc/generate_container_user#L7 the container tries to create a passwd file for the nss_wrapper. See also #98 

Why is this created in `/opt/app-root/etc/passwd` rather than /tmp? Logs I see indicate that the file could not be written:

```
/opt/app-root/etc/generate_container_user: line 10: /opt/app-root/etc/passwd: Permission denied
/opt/app-root/etc/generate_container_user: line 12: /opt/app-root/etc/passwd: Permission denied
```

**Comment by pkubatrh** [comment]
I dont see a difference between "using random UID" and "using custom UID" so afaik yes, both use cases are expect to have GID=0.

**Comment by goern** [comment]
I am running on OpenShift Master v3.9.40, Kubernetes Master v1.9.1+a0ce1bc657. I dont know which UID GID are used by OpenShift. I  will recheck.

**Comment by goern** [comment]
The problem does not persist, could it be related to a local configuration change in OpenShift?

**Comment by omron93** [comment]
> could it be related to a local configuration change in OpenShift?

I think UID/GID could be changed in SCC, so yes.
