### ISSUE TITLE
Update to Fedora 29

### ISSUE THREAD

**Issue by torsava** [sclorg/s2i-python-container#311]
It's time.

**Comment by frenzymadness** [comment]
I am working on Python 3.7 with Fedora 29. Does it make sense to update Python 2.7 to Fedora 29? Python 3.6 will stay on Fedora 28 because 3.6 is the default Python there.

**Comment by frenzymadness** [comment]
Python 2.7 containers are generated only for RHEL/Centos and there is no reason to change it now.

Python 3.7 is available with Fedora 29.
