### ISSUE TITLE
Generated documentation is not correct

### ISSUE THREAD

**Issue by frenzymadness** [sclorg/s2i-python-container#314]
Documentation generated from `src/README.md` should contain only usage examples for a platform which the Python version is generated for.

For example, there is no Python 3.5 in RHEL8 but you can find it in the readme: https://github.com/sclorg/s2i-python-container/tree/master/3.5#usage

**Comment by Lorquas** [comment]
+1 ; none of the usage examples for 3.7 work:  https://github.com/sclorg/s2i-python-container/blob/master/3.7/README.md

**Comment by frenzymadness** [comment]
Yes because examples are generated for Centos and RHEL but Python 3.7 is available only in Fedora yet.

I am gonna take a look on PR.
