### ISSUE TITLE
Make contributing easier

### ISSUE THREAD

**Issue by frenzymadness** [sclorg/s2i-python-container#315]
I would like to see a simple list of steps with commands I should do before I open a PR.

For example:
* Do your changes to src/ and multispec.yml
* Clean all generated content
* Generate all files from the source
* Check changes
* Build images (or only a few you changed)
* Tag images
* Run tests

And then open PR.

**Comment by omron93** [comment]
I think PRs are more than welcomed.

**Comment by frenzymadness** [comment]
I got it on my TODO list :slightly_smiling_face:

**Comment by torsava** [comment]
+1
