### ISSUE TITLE
Pipfile.lock in `src/test/pipenv-test-app/3.7`

### ISSUE THREAD

**Issue by frenzymadness** [sclorg/s2i-python-container#317]
There are several Pipfile and Pipfile.lock files in `src/test/pipenv-test-app/`, `src/test/pipenv-test-app/<python_version>` and `examples/pipenv-test-app/`.

It would be nice to reduce them and describe somewhere how to generate a new `Pipfile.lock` for a new Python version.

I did it for Python 3.7 this way:
```
$ cd examples/pipenv-test-app
# Update python_version in [requires] section in Pipfile
$ pipenv lock
$ cp Pipfile.lock ../../src/test/pipenv-test-app/3.7/
```

**Comment by torsava** [comment]
I agree we should document this, thanks for opening an issue for it. However, do you think we can reduce them? As in have only 1 Pipfile/.lock? I think we need to have different versions of packages for different Python versions. Do you think otherwise?

**Comment by frenzymadness** [comment]
I just misunderstood the hierarchy od `Pipfile` and `Pipfile.lock` files here. Their amount and placing are correct so I just add a comment to `Pipfile.lock` about how to create a new one for a new Python version.
