### ISSUE TITLE
Fedora/Python 3.7 image should still source scl_enable.

### ISSUE THREAD

**Issue by GrahamDumpleton** [sclorg/s2i-python-container#325]
In the `Dockerfile`` for Fedora/Python 3.7 image, it does:

```
# For Fedora scl_enable isn't sourced automatically in s2i-core
# so virtualenv needs to be activated this way
ENV BASH_ENV="${APP_ROOT}/bin/activate" \
    ENV="${APP_ROOT}/bin/activate" \
    PROMPT_COMMAND=". ${APP_ROOT}/bin/activate"
```

This should not be using `${APP_ROOT}/bin/activate` directly for these environment variables. It should still be using `/opt/app-root/etc/scl_enable`. This is because derived images which have added additional startup actions to the `scl_enable` script will now fail, since those steps will be skipped.

If changes are needed because actions to enable packages are different, or not required, it should be handled in the `scl_enable` script, and not by changing what these environment variables trigger.

**Comment by frenzymadness** [comment]
Could you please take a look at the PR?
