### ISSUE TITLE
SCL SQLite versions too old to work with latest Django versions.

### ISSUE THREAD

**Issue by GrahamDumpleton** [sclorg/s2i-python-container#333]
FYI. Looks like latest Django versions will not work any more if SQLite database is being used. Django has a version check on SQLite and the Python versions shipped bundle a version which is too old.

One example of this:

* https://github.com/WeblateOrg/weblate/issues/2875

The error will be:

```
ERROR Handled exception: ImproperlyConfigured: SQLite 3.8.3 or later is required (found 3.7.17).
```

**Comment by nijel** [comment]
Just to clarify: It's not Python version, it's version of the sqlite3 library.

**Comment by GrahamDumpleton** [comment]
SQLite is bundled with Python and that is used. So unless they have done work to separate things so the system SQLite is used, it is the Python version which is the issue.

**Comment by nijel** [comment]
On most Linux distributions, system SQLite is used instead of the bundled one and CentOS 7 has 3.7.17 which we see in the error message....

**Comment by frenzymadness** [comment]
Latest centos:
```
$ yum list installed | grep sqlite
sqlite.x86_64                             3.7.17-8.el7                  @CentOS 
$ python2
Python 2.7.5 (default, Jun 20 2019, 20:27:34) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> sqlite3.sqlite_version
'3.7.17'
```

So, we can pin Django to the older version or open a bug to update sqlite in Centos. Fedora 30 has sqlite 3.26.0, rawhide has 3.29. I think that the update would be much better.

**Comment by pkubatrh** [comment]
Note that in one of the more recent versions of sqlite there have been some ABI-changes, so updating to a newer version might not be possible in RHEL.

**Comment by jfmatth** [comment]
Where is this?

This is keeping me from moving my django project to OS

**Comment by frenzymadness** [comment]
The latest versions of RHEL/Centos 7 contain older SQLite (3.7.17) but RHEL/Centos 8 contains version 3.26.0 which should be fully compatible with the newest Django. We plan to add Centos 8 soon. In the meantime, you can use Fedora images.

**Comment by pkubatrh** [comment]
Hi @jfmatth

As far as I can tell the fix for this is really needed in the underlying rpm packages, so if you need this fixed for RHEL7 consider opening up a bugzilla report against the sqlite component.

However, be aware that (as I commented on previously) the sqlite version i RHEL7 is very old and backwards compatibility in sqlite is not really guaranteed (I remember one rebase that actually broke Django recently), so it might not be possible to update it.

**Comment by jfmatth** [comment]
@pkubatrh thanks for the response.

I guess Ill try the Fedora images or wait for RHEL 8

J
