### ISSUE TITLE
Pulling image error : How to work in Win 10 from behind corporate firewall env? 

### ISSUE THREAD

**Issue by scheung38** [sclorg/s2i-python-container#334]
We don't have github access from within corporate environment in Win 10. Like to use this for Flask app.

What is the syntax and where should I run s2i build if I initially download this repo into local desktop first. Because tried in local
s2i-python-container-master> s2i build https://github.com/sclorg/s2i-python-container.git - - context-dir=3.7/test/setup-test-app/ rhscl/python-37-rhel7 python-sample-app

Pulling image error: error from daemon: unauthorised: authentication required.

Because we cannot login to github from corporate network. 

Please advise how to run as I also tried to run by replacing http with local using dot

s2i build. - - context (same as above)

Pulling image error: pull access denied for rhscl/python-37-rhel7, repo does not exist or may require docker login

**Comment by frenzymadness** [comment]
To work with s2i Python containers, you need two things:

* Base docker image based on Fedora/RHEL/Centos with the right Python version for your needs
* Your source code

So the question is: do you have access to Docker hub to pull down base docker image?

The simplest example of use is: `s2i build <path_to_source_code> <image_name> <final_container_name>` - for example `s2i build examples/django-test-app centos/python-36-centos7 my-django-app`
This command downloads image `python-36-centos7` as a base, builds your application on top of it and creates new image `my-django-app`.

Try this simple example and let me know if it does not work for you.

**Comment by scheung38** [comment]
It is going to get the same firewall issue as you are telling me to do the same command as when I previously tried.

I like to know how to reference a local source of image instead as behind firewall login to Github is not allowed

**Comment by frenzymadness** [comment]
Your problem is not caused by restricted access to Github because you don't have to use this repository at all.
You need source code of your application. I guess you have it. If you just want to test it, feel free to play around with some examples in this repository or use them as an inspiration.
The second thing you need is a docker image. That's the reason why I asked whether you have access to Docker hub repository where you can pull S2I Python images from.

**Comment by frenzymadness** [comment]
You can try to pull the centos Python 3.6 image from Docker hub via `docker pull centos/python-36-centos7`.

**Comment by scheung38** [comment]
Rhel equivalent?

I was able to build a very simple flask app using python-36-centos7 but 650MB??

**Comment by geordgez** [comment]
What does your directory structure look like for the `s2i`-built image?

**Comment by scheung38** [comment]
Hi there 
I cloned your project but after 
S2i build. centos/python-36-centos7 hello-world
Could not reach URL https://pypi.python.org/simple/flask: there was a problem confirming ssl 
This is related to corporate firewall so I also have 
Pip conf [Global] Index-url = http://corporate.com/artifactory

Sent from Yahoo Mail on Android 
 
  On Mon, 15 Jul 2019 at 14:02, George Zeng<notifications@github.com> wrote:   
What does your directory structure look like for the s2i-built image?

**Comment by frenzymadness** [comment]
Hi.

If you need to use pip with some special configuration, add the `pip.conf` file to your application and then set an environment variable `PIP_CONFIG_FILE` in `.s2i/environment` file.

For example:
```
$ ls -a
.  ..  pip.conf  requirements.txt  .s2i  wsgi.py
$ cat pip.conf 
[global]
index-url = https://example.org/PYPI
$ cat .s2i/environment 
PIP_CONFIG_FILE=./pip.conf
```

Take a look at [pip docs](https://pip.pypa.io/en/stable/user_guide/#config-file) and also [s2i docs](https://github.com/openshift/source-to-image).

**Comment by frenzymadness** [comment]
Did my last comment help you? Can I help you more?

**Comment by scheung38** [comment]
I will try but this image also takes care about init just like Phusion image does to make sure zombie processes are reaped?

**Comment by scheung38** [comment]
it works, but based on a single flask starter project the image size is around 651MB???

**Comment by frenzymadness** [comment]
> I will try but this image also takes care about init just like Phusion image does to make sure zombie processes are reaped?

Optional init wrapper can be enabled by `ENABLE_INIT_WRAPPER`. See the documentation: https://github.com/sclorg/s2i-python-container/tree/master/3.7#environment-variables

**Comment by frenzymadness** [comment]
> it works, but based on a single flask starter project the image size is around 651MB??? Original flask app using Dockerfile for a single Flask app was 92MB, but now with s2i it is 655MB?

I think that this was answered in the other issue. It's a bug and we are working on it.

> Without the CMD explicitly built into the Dockerfile, how does s2i know what initial CMD command to run, as this is different for flask as opposed to another python web app in each case?
> 
> Does it do this under the hood
> 
> CMD["/sbin/my_init"] ?

Please, take a look at the documentation first: https://github.com/sclorg/s2i-python-container/tree/master/3.7#environment-variables

You can use shell script, Python script or Python module as an entry point of your application. There are also some automatic run strategies you can use: https://github.com/sclorg/s2i-python-container/tree/master/3.7#run-strategies
