### ISSUE TITLE
What is the expected image size for Flask starter app?  Got huge image size. 

### ISSUE THREAD

**Issue by scheung38** [sclorg/s2i-python-container#340]
A basic flask app using python-36-rhel7 results in 1.9GB?

is it not defeating the purpose or slim docker images in the first place?

**Comment by pkubatrh** [comment]
Hi @scheung38 

the current image size is caused by a bug during the build process, when some of the images did not clean all of yum's cached data the right way.
Python image's layer is actually not affected by this (as it is one of the few images that did the clean-up correctly all along), but unfortunately the s2i-core and s2i-base, which the python images are using as their base layers, have been affected by the issue.

The issue for the s2i-core and s2i-base images is tracked over at https://github.com/sclorg/s2i-base-container/pull/192 and you should see a fix for python-36 in the near future.

**Comment by scheung38** [comment]
Hi @pkubatrh then what is the normal expected starter flask app image size is expected to be?

**Comment by pkubatrh** [comment]
Yeah, an image size of about 700MB seems about right for the result. Please note these images are not optimized for size, but rather designed generic enough to be used for various use cases in Openshift (= without root access), so they have a lot of build-time dependencies built in.
An image created for one specific use case from scratch will always be a lot smaller.

>Also s2i is building from repo only and only from local machine? If that is the case then every time I need to test locally, i would need to push to repo first?

Not sure what you mean by repo here. A git repository? Iirc `s2i` is able to build from local sources, but if you pass a git repository to the build command it will try to sync with the online sources instead.

If you want to work around the use of `s2i` - you can do that. Just build on top of the python image directly via a Dockerfile and copy the sources into the correct places as expected by the [assemble](https://github.com/sclorg/s2i-python-container/blob/master/src/s2i/bin/assemble) and [run](https://github.com/sclorg/s2i-python-container/blob/master/src/s2i/bin/run) scripts.

Upstream [source-to-image](https://github.com/openshift/source-to-image) version also had a `--as-dockerfile` option that could generate a Dockerfile for you. Another alternative is taking a look at our test lib where we do it [similarly](https://github.com/sclorg/container-common-scripts/blob/master/test-lib.sh#L440).

**Comment by scheung38** [comment]
repo as in GitHub, that it is only able to build from latest pushed code in GitHub. 

So even if I start and s2i create from scratch, what sort of image size I should expect from Flask starter app?

**Comment by frenzymadness** [comment]
I probably don't understand what you need. If you need to have images as small as possible, you should use some really small image as a base (centos ~70 MB: https://hub.docker.com/_/centos?tab=tags or Fedora ~66 MB https://hub.docker.com/_/fedora?tab=tags) and create your own docker file with minimal installation.

**Comment by frenzymadness** [comment]
S2I images are universal and therefore always bigger than single-purpose images.
