### ISSUE TITLE
numpy-test-app test case failing for python-27 image

### ISSUE THREAD

**Issue by pkubatrh** [sclorg/s2i-python-container#341]
This is due to the fact that the latest upstream version does not support Python 2.7 anymore:
https://docs.scipy.org/doc/numpy/release.html#numpy-1-17-0-release-notes

Test logs: https://gist.github.com/rhscl-bot/80930281f4eb45ea9dc75b6d8a9114db

**Comment by pkubatrh** [comment]
I guess we could pin the numpy version to 1.16 for python 2.7? WDYT @torsava @frenzymadness

**Comment by frenzymadness** [comment]
I think that this is the best solution. Numpy 1.16 will receive all bugfixes till the end of the year. I'll prepare a PR.
