### ISSUE TITLE
python27 pip install uwsgi failed

### ISSUE THREAD

**Issue by flask-rabmq** [sclorg/s2i-python-container#345]
Sending build context to Docker daemon  4.096kB
Step 1/7 : FROM centos/python-27-centos7:20190806-27a5076
 ---> 899fcfa5ddde
Step 2/7 : RUN pip install uwsgi
 ---> Running in 90861fc3a6c4
Traceback (most recent call last):
  File "/opt/app-root/bin/pip", line 7, in <module>
    from pip import main
  File "/opt/app-root/lib/python2.7/site-packages/pip/__init__.py", line 4, in <module>
    import logging
  File "/opt/rh/python27/root/usr/lib64/python2.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref, collections
  File "/opt/rh/python27/root/usr/lib64/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
The command '/bin/sh -c pip install uwsgi' returned a non-zero code: 1

**Comment by frenzymadness** [comment]
Could you please provide us more information? What kind of application are you trying to build? I've tried our `examples/npm-virtualenv-uwsgi-test-app` with the lastest image `centos/python-27-centos7:latest` and also with `:20190806-27a5076` and it works for me.

Do you have some minimal reproducer, please?

**Comment by flask-rabmq** [comment]
I want to build python+flask+uswgi app.

Dockerfile:
FROM centos/python-27-centos7

RUN pip install uwsgi
# 添加标签说明
LABEL author="chenxiaolong" email="214443354@qq.com"  purpose="centos7+nginx+uwsgi+Python27基础镜像"

USER root

ENV nginxversion="1.14.0-1" \
    os="centos" \
    osversion="7" \
    elversion="7_4"

RUN yum install -y wget openssl sed python-devel&&\
    yum -y autoremove &&\
    yum clean all &&\
    wget http://nginx.org/packages/$os/$osversion/x86_64/RPMS/nginx-$nginxversion.el$elversion.ngx.x86_64.rpm &&\
    rpm -iv nginx-$nginxversion.el$elversion.ngx.x86_64.rpm

RUN pip install uwsgi


result:
Sending build context to Docker daemon  4.096kB
Step 1/7 : FROM centos/python-27-centos7
 ---> 899fcfa5ddde
Step 2/7 : RUN pip install uwsgi
 ---> Running in 62c48ec5a300
Traceback (most recent call last):
  File "/opt/app-root/bin/pip", line 7, in <module>
    from pip import main
  File "/opt/app-root/lib/python2.7/site-packages/pip/__init__.py", line 4, in <module>
    import logging
  File "/opt/rh/python27/root/usr/lib64/python2.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref, collections
  File "/opt/rh/python27/root/usr/lib64/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
The command '/bin/sh -c pip install uwsgi' returned a non-zero code: 1

**Comment by frenzymadness** [comment]
You don't have to create your own dockerfile when using S2I. Take a look at [this example](https://github.com/sclorg/s2i-python-container/tree/master/examples/npm-virtualenv-uwsgi-test-app), how to prepare your application (eg. place your requirements into `requirements.txt` file).

Then you just need to build your application with s2i command, for example: `s2i build . centos/python-27-centos7 myappname` (the dot means current working directory).

**Comment by pkubatrh** [comment]
@flask-rabmq iirc the python27 SCL is not enabled when directly building on top of the image like that. You can wrap the `pip` call into `bash` (`RUN bash -c "pip install uwsgi"`) and the SCL will be enabled for the command. But using the image through s2i, as Lumir suggested, is probably easier.
