### ISSUE TITLE
Slow package loading when using UPGRADE_PIP_TO_LATEST

### ISSUE THREAD

**Issue by CarolineBt** [sclorg/s2i-python-container#358]
Hello,

I am using Python 3.5 image on Openshift and I use requirements.txt file to download and install my packages. I need to install cryptography library, and this library needs updated version of setuptools.

I found about the UPGRADE_PIP_TO_LATEST environment variable that permits me to downlaod and install setuptools before installing other packages, which is great. However, using this environment variable also increased drastically my Build time: instead of less than 3 minutes when I do not use this variable, the Build takes almost 30 minutes when I use it...

I did not find anything about this kind of issue, is this normal? How could I solve this?

Thank you,

Caroline

**Comment by frenzymadness** [comment]
Hello, Caroline.

That sounds really strange to me. I'll investigate it. Could you please provide us some reproducer. For example, is your application publicly available so I can try to build a container for it manually? If not, could you please send us only the important parts like `requirements.txt` and such.

Thank you. Lumír

**Comment by frenzymadness** [comment]
I've tried to reproduce your issue. I've built django-test-app from our examples with Python 3.5 centos7 image and with/without `UPGRADE_PIP_TO_LATEST` set. The difference is only 8 seconds in my case which it's the exact time needed to download and upgrade pip/setuptools/wheel.
