### ISSUE TITLE
Testing of a library version with Python 2.7

### ISSUE THREAD

**Issue by frenzymadness** [sclorg/s2i-python-container#360]
Test [npm-virtualenv-uwsgi-test-app](https://github.com/sclorg/s2i-python-container/blob/master/examples/npm-virtualenv-uwsgi-test-app/app.sh#L31) tests that we have the latest version of libraries installed in a virtual environment.

This won't work anymore because Python 2.7 doesn't get the latest versions due to its EOL. For example, the latest setuptools is 45.0.0 but the Python 2.7 support ends on 44.0.0. https://github.com/pypa/setuptools/blob/master/CHANGES.rst#v4500

It is possible to get the version compatibility info from the PyPI API but it won't be easy to implement:

setuptools 45
```
"45.0.0": [
…
        "requires_python": ">=3.5",
```

setuptools 44
```
    "44.0.0": [
…
        "requires_python": "!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,>=2.7",
```
I'd say that better would be to remove this part of the test.

**Comment by andyfeller** [comment]
Will second having an issue with `UPGRADE_PIP_TO_LATEST` upgrading to setuptools>=45.0.0 breaks Python 2.7 usage and something to fix it would be appreciated.

**Comment by frenzymadness** [comment]
I might know where the problem comes from and I try to reproduce it next week. It seems that the version of pip/setuptools installed in the container is too old to support the "supported pythons" feature which means that the setuptools/pip stack is updated to the latest version of setuptools which does not support Python 2 but this fact is not known before the update.

**Comment by frenzymadness** [comment]
The solution here might be to do an update in two steps:
1. Update to the latest version supported by the Python 2.
2. Update to the latest version. This step would be performed only for Python 3 because the newer setuptools/pip stack would know that there is no newer version with Python 2 support available.

**Comment by andyfeller** [comment]
@frenzymadness TIL!  Thanks for the theory there; definitely need to bone up on that feature as I saw situations where this was and wasn’t an issue but didn’t know where to start looking
