### ISSUE TITLE
app.sh is not executable by pod user

### ISSUE THREAD

**Issue by leogout** [sclorg/s2i-python-container#371]
Hello, I can't seem to be able to run `app.sh` from the .s2i/run script as `app.sh` does not have execution permissions.  
I found the exact same problem in a related post [here on stackoverflow](https://stackoverflow.com/questions/46091601/cannot-chmod-file-on-openshift-online-v3-operation-not-permitted). Also [here is a veeery frustrating post](https://access.redhat.com/solutions/4221981) which seems to adress this exact issue but it is inaccessible to non premium users like myself...

The solution brought in the stackoverflow post (override the .s2i/run to chmod the app.sh script) seems legit but I don't think I should have to do that in the first place... Why is my app.sh file non executable ? It seems way too obvious to be a problem coming from your image. Also I can't seem to be able to find anything else related to this issue. I'm pretty sure I'm missing something here.

By the way thank you for your great work on this s2i image, it's a huge help and I wouldn't be able to make my own in a million years.

Cheers !

**Comment by fridex** [comment]
Is there any reason why you don't setup the executable bit and commit the file with changed mode into git?

```
chmod +x app.sh
git commit app.sh -m "some message"
git push
```

**Comment by leogout** [comment]
Thank you for your answer, my app.sh file was indeed executable but git wasn't tracking that information when adding / commiting. I just forced it with `git update-index --chmod=+x app.sh`. The build is currently running, I'll keep you updated.

**Comment by leogout** [comment]
All right that worked, thank you very much. I thought that runnong `fix-permissions` on all the files under `/opt/app-root/src` was messing with the ones I had previously set. I'll make sure to answer this stackoverflow post then.

**Comment by fridex** [comment]
> All right that worked, thank you very much. I thought that runnong `fix-permissions` on all the files under `/opt/app-root/src` was messing with the ones I had previously set. I'll make sure to answer this stackoverflow post then.

Awesome, glad to help :+1:
