### ISSUE TITLE
Support poetry as an alternative for package installation

### ISSUE THREAD

**Issue by AWhetter** [sclorg/s2i-python-container#430]
poetry is a tool much like pipenv and it supports a similar feature set to pipenv. Most notably, it supports lock files. It's less popular than pipenv but it's still a widely used tool.

Currently we make use of poetry by having an extra step in our developer workflow where we get poetry to produce a requirements.txt file, but we lose out on some of the benefits of lock files this way. Ideally would we be able to get the assemble script to install our dependencies from our lock file using poetry.

**Comment by fridex** [comment]
You can enable [micropipenv](https://github.com/thoth-station/micropipenv) (by providing `ENABLE_MICROPIPENV=1`) which should install dependencies from poetry specific files.

**Comment by AWhetter** [comment]
So it does! I had no idea. Thanks for pointing this out.
