### ISSUE TITLE
pip upgradation

### ISSUE THREAD

**Issue by Namratha4** [sclorg/s2i-python-container#439]
Pls upgrade pip to **21.1** version. On openshift, it is by default considering the 19.3.1 version due to which some libraries are not able to get downloaded from nexus.

**Comment by frenzymadness** [comment]
Could you please share more details? What problems do you have with pip 19.3.1? What does "some libraries are not able to get downloaded from nexus" means? Do you know that you can use `UPGRADE_PIP_TO_LATEST` to get the latest pip? See: https://github.com/sclorg/s2i-python-container/tree/master/3.8#environment-variables

**Comment by frenzymadness** [comment]
All Python 3 images should now have the latest pip from Fedora 34 which is 21.0.1. If this version is too old for you, you can still use `UPGRADE_PIP_TO_LATEST` environment variable.
Feel free to reopen this issue if you need anything.
