### ISSUE TITLE
Container comand exits silently when APP_MODULE=app:app

### ISSUE THREAD

**Issue by yrro** [sclorg/s2i-python-container#442]
I ran into a usability issue when helping a user get their application running on OpenShift.

Their application code is in `app.py`, so we set `APP_MODULE=app:app` and were confused when the `run` script exited silently after launching the app.

This happened because the `run` sees that `APP_FILE` is not set, and so defaults it to `app.py`. The module then gets launched as a script, and since it only consists of declarations, the script exits silently.

Maybe `APP_MODULE` being set should prevent the `APP_SCRIPT`/`APP_FILE` paths from being taken. This precedence makes sense to me:

1. If more than one of `APP_FILE`, `APP_SCRIPT` and `APP_MODULE` are set, error out
1. Launch using whichever of `APP_*` were set
1. Try to launch WSGI app `wsgi:app`
1. Try to launch script `app.sh`
1. Try to launch script `app.py`

I guess detecting the existence of `wsgi:app` is a bit tricky though. One way to do it would be to test the exit status of `python -c import wsgi; wsgi.app`. Of course that might fail for other reasons, and then the fallbacks of `app.sh` and `app.py` would be triggered...

**Comment by frenzymadness** [comment]
Thanks for the report. It definitely makes sense that when one of the `APP_` variables is set, we should use it and ignore the defaults. I hope I'll find a time for this soon. The fix has to be implemented in https://github.com/sclorg/s2i-python-container/blob/master/src/s2i/bin/run.

**Comment by frenzymadness** [comment]
I'm gonna try to fix this in #444

**Comment by frenzymadness** [comment]
Would you be able to review the proposed fix?

**Comment by yrro** [comment]
Looks good to me, thanks.

**Comment by frenzymadness** [comment]
This has been fixed in the mentioned PR.
