### ISSUE TITLE
unable to use alternative ports. only 8080 is used

### ISSUE THREAD

**Issue by evanshortiss** [sclorg/s2i-python-container#446]
I've run into an issue where my gunicorn application refused to listen on any port besides 8080.

It seems [that this line in `run`](https://github.com/sclorg/s2i-python-container/blob/master/3.8/s2i/bin/run#L98) supersedes all other settings.

Perhaps this should be configurable via a runtime environment variable? I assume the reason the `--bind` is passed is because a developer might not have `bind` in their config file?

**Comment by frenzymadness** [comment]
Thanks for the report!

The question here is whether it makes sense to remove the --bind entirely and rely on the config or add an env variable to specify a port to listen on. We also use the default port for Django.

What about this:
1. If there is a config file and if it contains "bind", do not use the --bind CLI parameter at all
2. if there is not a config file or it does not contain "bind", use `--bind 0.0.0.0:$PORT`where `PORT` is
    3. either configured as an environment variable or
    4. default - 8080

This way, we can make it flexible for different gunicorn configurations and also more flexible for Django.

What do you think about it?

**Comment by evanshortiss** [comment]
What you've described sounds like the ideal scenario IMO. Flexible, but uses sensible defaults 👍

**Comment by frenzymadness** [comment]
I should have time to implement this next week.

**Comment by evanshortiss** [comment]
BTW, this is not a blocker for me so no time pressure from my side!

I appreciate you taking care of it for future usage/users though! 🙏

**Comment by frenzymadness** [comment]
@evanshortiss could you please take a look at my implementation in #450 ? It's ready for merge from my point of view but you might have something to say.

**Comment by evanshortiss** [comment]
@frenzymadness just tested the 3.6 version and it worked perfectly with the gunicorn app I have. Fantastic work! Docs make the usage nice and clear too 👍 

Thank you!

**Comment by frenzymadness** [comment]
Thank you!
