### ISSUE TITLE
install python packages out of s2i virtualenv

### ISSUE THREAD

**Issue by pacospace** [sclorg/s2i-python-container#466]
Hi all,

when trying to install packages, we (thoth team) don't want to pollute user environment, so we run using `/usr/bin/pip3`, but by default they are still installed in app-root.

Is there a way to change this behaviour with an env variable? Or is there any solution to this problem?

Source of DockerFile: https://github.com/thoth-station/s2i-thoth/blob/725a20f808136ae82f2b5987f6d6df8e69787926/ubi8-py38/Dockerfile#L35

**Comment by pacospace** [comment]
Related-To: https://github.com/thoth-station/s2i-thoth/issues/201

**Comment by frenzymadness** [comment]
I've tried to reproduce the issue in the simplest way possible running in the UBI 8 Python 3.9 container:
```
(app-root) pip3 -V
pip 21.0.1 from /opt/app-root/lib64/python3.9/site-packages/pip (python 3.9)
(app-root) /usr/bin/pip3 -V
pip 20.2.4 from /usr/lib/python3.9/site-packages/pip (python 3.9)
(app-root) /usr/bin/pip3 install tqdm
Defaulting to user installation because normal site-packages is not writeable
Collecting tqdm
  Downloading tqdm-4.61.2-py2.py3-none-any.whl (76 kB)
     |████████████████████████████████| 76 kB 804 kB/s 
Installing collected packages: tqdm
Successfully installed tqdm-4.61.2
(app-root) pip3 list
Package    Version
---------- -------
pip        21.0.1
setuptools 50.3.2
WARNING: You are using pip version 21.0.1; however, version 21.2.1 is available.
You should consider upgrading via the '/opt/app-root/bin/python3.9 -m pip install --upgrade pip' command.
```
It seems that it properly installs the package outside the virtual environment. I'll try to reproduce your exact steps soon.

Side question: Have you considered installing dependencies from RPM packages?

**Comment by pacospace** [comment]
> I've tried to reproduce the issue in the simplest way possible running in the UBI 8 Python 3.9 container:
> 
> ```
> (app-root) pip3 -V
> pip 21.0.1 from /opt/app-root/lib64/python3.9/site-packages/pip (python 3.9)
> (app-root) /usr/bin/pip3 -V
> pip 20.2.4 from /usr/lib/python3.9/site-packages/pip (python 3.9)
> (app-root) /usr/bin/pip3 install tqdm
> Defaulting to user installation because normal site-packages is not writeable
> Collecting tqdm
>   Downloading tqdm-4.61.2-py2.py3-none-any.whl (76 kB)
>      |████████████████████████████████| 76 kB 804 kB/s 
> Installing collected packages: tqdm
> Successfully installed tqdm-4.61.2
> (app-root) pip3 list
> Package    Version
> ---------- -------
> pip        21.0.1
> setuptools 50.3.2
> WARNING: You are using pip version 21.0.1; however, version 21.2.1 is available.
> You should consider upgrading via the '/opt/app-root/bin/python3.9 -m pip install --upgrade pip' command.
> ```
> 
> It seems that it properly installs the package outside the virtual environment. I'll try to reproduce your exact steps soon.
> 
Thanks a lot @frenzymadness! 

here is the image built running ` podman build --tag fmurdaca-dev -f ./ubi8-py38/Dockerfile` https://quay.io/repository/pacospace/ubi8-py38?tab=tags

> Side question: Have you considered installing dependencies from RPM packages?
Actually not! cc @fridex

**Comment by frenzymadness** [comment]
> > Side question: Have you considered installing dependencies from RPM packages?
> 
> Actually not! cc @fridex

Now I see that the list of packages is very long and I'm sure that a lot of them aren't available in RHEL.

I know where the problem is. You are setting the `MICROPIPENV_*` variables to modify its behavior but you are setting them to `curl` command instead of the python/micropipenv - the environment variables are not preserved after the pipe, see this simple reproducer:

```shell
FOO="bar" yes | echo "xxx $FOO xxx"
xxx  xxx
```

A few more questions out of my curiosity. Why do you download the requirements.txt file if you can just copy it to the image? Also, why don't you maintain your own version of the assemble script instead of maintaining the patch and manipulating it in the build process?

**Comment by pacospace** [comment]
> > > Side question: Have you considered installing dependencies from RPM packages?
> > 
> > 
> > Actually not! cc @fridex
> 
> Now I see that the list of packages is very long and I'm sure that a lot of them aren't available in RHEL.
> 
> I know where the problem is. You are setting the `MICROPIPENV_*` variables to modify its behavior but you are setting them to `curl` command instead of the python/micropipenv - the environment variables are not preserved after the pipe, see this simple reproducer:
> 
> ```shell
> FOO="bar" yes | echo "xxx $FOO xxx"
> xxx  xxx
> ```

Thanks @frenzymadness!! I rebuilt the image (https://quay.io/repository/pacospace/ubi8-py38?tab=tags) to test and packages are not installed there anymore as expected, but pip is not updated to the version mentioned in https://github.com/thoth-station/s2i-thoth/blob/725a20f808136ae82f2b5987f6d6df8e69787926/ubi8-py38/Dockerfile#L33

```
(app-root) ls /usr/lib/python3.8/site-packages/
easy_install.py  pip-19.3.1.dist-info  __pycache__  setuptools-41.6.0.dist-info
pip		 pkg_resources	       setuptools
(app-root) ls /opt/app-root/lib/python3.8/site-packages/
easy_install.py  pip-20.3.3.dist-info  __pycache__  setuptools-41.6.0.dist-info
pip		 pkg_resources	       setuptools
```


> 
> A few more questions out of my curiosity. Why do you download the requirements.txt file if you can just copy it to the image? Also, why don't you maintain your own version of the assemble script instead of maintaining the patch and manipulating it in the build process?

Very good questions, I think we can definitely improve on this. I only recently started contributing to the s2i-thoth repository so maybe @fridex @hnalla might have more explanations on this :)

**Comment by pacospace** [comment]
> > > Side question: Have you considered installing dependencies from RPM packages?
> > 
> > 
> > Actually not! cc @fridex
> 
> Now I see that the list of packages is very long and I'm sure that a lot of them aren't available in RHEL.
> 
> I know where the problem is. You are setting the `MICROPIPENV_*` variables to modify its behavior but you are setting them to `curl` command instead of the python/micropipenv - the environment variables are not preserved after the pipe, see this simple reproducer:
> 
> ```shell
> FOO="bar" yes | echo "xxx $FOO xxx"
> xxx  xxx
> ```
> 
> A few more questions out of my curiosity. Why do you download the requirements.txt file if you can just copy it to the image? 

I actully saw that for the new image ubi-py39, we are doing this, so it's just a matter of adjusting the other: https://github.com/thoth-station/s2i-thoth/blob/725a20f808136ae82f2b5987f6d6df8e69787926/ubi8-py39/Dockerfile#L29

> Also, why don't you maintain your own version of the assemble script instead of maintaining the patch and manipulating it in the build process?

**Comment by pacospace** [comment]
> > > > Side question: Have you considered installing dependencies from RPM packages?
> > > 
> > > 
> > > Actually not! cc @fridex
> > 
> > 
> > Now I see that the list of packages is very long and I'm sure that a lot of them aren't available in RHEL.
> > I know where the problem is. You are setting the `MICROPIPENV_*` variables to modify its behavior but you are setting them to `curl` command instead of the python/micropipenv - the environment variables are not preserved after the pipe, see this simple reproducer:
> > ```shell
> > FOO="bar" yes | echo "xxx $FOO xxx"
> > xxx  xxx
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > A few more questions out of my curiosity. Why do you download the requirements.txt file if you can just copy it to the image?
> 
> I actully saw that for the new image ubi-py39, we are doing this, so it's just a matter of adjusting the other: https://github.com/thoth-station/s2i-thoth/blob/725a20f808136ae82f2b5987f6d6df8e69787926/ubi8-py39/Dockerfile#L29
> 
> > Also, why don't you maintain your own version of the assemble script instead of maintaining the patch and manipulating it in the build process?

but it should be `COPY ./requirements.txt /opt/app-root/src/requirements.txt` actually for micropipenv to find it. I will adjust that as well.

**Comment by frenzymadness** [comment]
> Thanks @frenzymadness!! I rebuilt the image (https://quay.io/repository/pacospace/ubi8-py38?tab=tags) to test and packages are not installed there anymore as expected, but pip is not updated to the version mentioned in https://github.com/thoth-station/s2i-thoth/blob/725a20f808136ae82f2b5987f6d6df8e69787926/ubi8-py38/Dockerfile#L33
> 
> ```
> (app-root) ls /usr/lib/python3.8/site-packages/
> easy_install.py  pip-19.3.1.dist-info  __pycache__  setuptools-41.6.0.dist-info
> pip		 pkg_resources	       setuptools
> (app-root) ls /opt/app-root/lib/python3.8/site-packages/
> easy_install.py  pip-20.3.3.dist-info  __pycache__  setuptools-41.6.0.dist-info
> pip		 pkg_resources	       setuptools
> ```

It is but in a different folder. If you run pip as root, it installs packages to `/usr/local/lib/python3.8/site-packages/` to prevent conflicts with system packages. And the main binary uses the newest version:
```
(app-root) /usr/bin/pip3 -V
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
pip 20.3.3 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)
```

**Comment by pacospace** [comment]
> > Thanks @frenzymadness!! I rebuilt the image (https://quay.io/repository/pacospace/ubi8-py38?tab=tags) to test and packages are not installed there anymore as expected, but pip is not updated to the version mentioned in https://github.com/thoth-station/s2i-thoth/blob/725a20f808136ae82f2b5987f6d6df8e69787926/ubi8-py38/Dockerfile#L33
> > ```
> > (app-root) ls /usr/lib/python3.8/site-packages/
> > easy_install.py  pip-19.3.1.dist-info  __pycache__  setuptools-41.6.0.dist-info
> > pip		 pkg_resources	       setuptools
> > (app-root) ls /opt/app-root/lib/python3.8/site-packages/
> > easy_install.py  pip-20.3.3.dist-info  __pycache__  setuptools-41.6.0.dist-info
> > pip		 pkg_resources	       setuptools
> > ```
> 
> It is but in a different folder. If you run pip as root, it installs packages to `/usr/local/lib/python3.8/site-packages/` to prevent conflicts with system packages. And the main binary uses the newest version:
> 
> ```
> (app-root) /usr/bin/pip3 -V
> WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
> Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
> To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
> pip 20.3.3 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)
> ```

thanks @frenzymadness!!

**Comment by frenzymadness** [comment]
Do you have more questions?

**Comment by pacospace** [comment]
> Do you have more questions?

All good @frenzymadness, thank you very much for all help, support and explanations!!

**Comment by frenzymadness** [comment]
You are welcome. Feel free to open another issue in case of need or contact me on other channels.
