### ISSUE TITLE
pip install . is not run if setup.cfg is present

### ISSUE THREAD

**Issue by yrro** [sclorg/s2i-python-container#479]
Following the [Packaging Python Projects](https://packaging.python.org/tutorials/packaging-projects/) leads you down the road of creating a `pyproject.toml` file (which declares that setuptools is used to build the project) and a `setup.cfg` file, which appears to be a newer alternative to `setup.py`.

I noticed that the `assemble` script only runs `pip install .` if `setup.py` is present, so I had to convert my `setup.cfg` file to a `setup.py` file. No big deal. But it would be nice if I could have kept the static `setup.cfg` file.

I don't know if it would be better to change the `assemble` script to check for `setup.cfg` as well, or whether it should be looking for a `pyproject.toml` file (since I think projects should put stuff in there that tells `pip` (or other package managers) how to build the project) and then fall back to `setup.py` (for projects that implicity use setuptools without declaring such in `pyproject.toml`).

**Comment by frenzymadness** [comment]
What Python version and platform combination do you prefer?

**Comment by yrro** [comment]
Sorry - didn't get around to trying this myself. But I am 99% sure your test reproduces what I'm trying to do exactly. Thanks :)
