### ISSUE TITLE
Minimal 3.9 container image is not available

### ISSUE THREAD

**Issue by frenzymadness** [sclorg/s2i-python-container#481]
@phracek do you have a plan to add a GH Action here to push the 3.9-minimal container image to quay.io? From my point of view, this is the last piece of this effort missing.

**Comment by frenzymadness** [comment]
Fixed in #485

**Comment by torsava** [comment]
I can successfully pull the image from quay.io:

    podman pull quay.io/sclorg/python-39-minimal:el8

However, without first looking up the tag `el8`, it gives me an error:

    podman pull quay.io/sclorg/python-39-minimal
    Trying to pull quay.io/sclorg/python-39-minimal:latest...
    Error: initializing source docker://quay.io/sclorg/python-39-minimal:latest: reading manifest latest in quay.io/sclorg/python-39-minimal: manifest unknown: manifest unknown

Hi, @phracek, could we include the `latest` tag as well, so that people get an image even without knowing the precise tag?

**Comment by phracek** [comment]
Hi @torsava 

It was agreed at the meeting, that the latest tag will not be used. However. Adding latest to the line https://github.com/sclorg/s2i-python-container/blob/master/.github/workflows/build-and-push-minimal.yml#L70 is super simple.

As soon as the minimal image will use other tags, then the latest will not be valid.
@hhorak @pkubatrh WDYT?

**Comment by hhorak** [comment]
I cannot remember whether we talked about not using `latest` specifically, was there some reason? It would actually make sense to me as well. If we only have `:el8` now, then `:latest` would be the same as `:el8` tag, and once there is something like `:el9`, we would move the `:latest` to match `:el9` (even if we keep maintaining `:el8`, which we might decide not to). Or is this not a good idea from some reason?

**Comment by torsava** [comment]
We discussed this on the meeting and decided to implement the `latest` tag. @phracek please make it so. :)

**Comment by phracek** [comment]
This should be solved by #492

**Comment by torsava** [comment]
Thank you, @phracek.

That makes our 3.9-minimal container readily available, so I'm closing this issue, great work @frenzymadness !

Last thing to do is to write an article, which I have on my todo list..
