### ISSUE TITLE
setuptools version update?

### ISSUE THREAD

**Issue by pacospace** [sclorg/s2i-python-container#484]
Hi everybody,

I recently encountered an issue with an s2i base image: https://github.com/thoth-station/thoth-ops-infra/issues/50. I was wondering what are the current constraints on setuptools version? Is there any plan to update it?

Thank you in advance for all support and answer.

**Comment by frenzymadness** [comment]
Do you mean Python setuptools? Are you using s2i-python container image or s2i-base directly? In s2i-python, there is an option to update pip/setuptools/wheel as a part of the build process.

**Comment by frenzymadness** [comment]
By default, setuptools version should be the same as it is in the OS as an RPM package - even in the virtual environments. Do you use Fedora or RHEL/Centos?

**Comment by pacospace** [comment]
> By default, setuptools version should be the same as it is in the OS as an RPM package - even in the virtual environments. Do you use Fedora or RHEL/Centos?

I'm using s2i-thoth based base images (s2i-python and ubi8), in particular: https://github.com/thoth-station/s2i-thoth/blob/master/ubi8-py38/Dockerfile available at https://quay.io/repository/thoth-station/s2i-thoth-ubi8-py38

**Comment by pacospace** [comment]
> Do you mean Python setuptools? Are you using s2i-python container image or s2i-base directly? In s2i-python, there is an option to update pip/setuptools/wheel as a part of the build process.

Yes python setuptools sorry! What is the option? Thanks a lot @frenzymadness!!

**Comment by frenzymadness** [comment]
Usually, you can use "UPGRADE_PIP_TO_LATEST", see: https://github.com/sclorg/s2i-python-container/tree/master/3.8#environment-variables

Even you are adjusting the assemble script in your container image heavily, the part handling this option should still be there and it should still work. You can also update your Dockerfile to install whatever version you need as you already doing for pip (just do it inside the virtual environment).

Let me know if I can help you more.

**Comment by pacospace** [comment]
> Usually, you can use "UPGRADE_PIP_TO_LATEST", see: https://github.com/sclorg/s2i-python-container/tree/master/3.8#environment-variables
> 
> Even you are adjusting the assemble script in your container image heavily, the part handling this option should still be there and it should still work. You can also update your Dockerfile to install whatever version you need as you already doing for pip (just do it inside the virtual environment).
> 
> Let me know if I can help you more.

Thanks @frenzymadness! I will check on that!

**Comment by frenzymadness** [comment]
I'm closing this issue now. If you need help, feel free to open a new one or reopen this one.
