### ISSUE TITLE
Switch Fedora tests to something newer

### ISSUE THREAD

**Issue by frenzymadness** [sclorg/s2i-python-container#495]
Currently, we cannot run tests for Fedora 35 here because the docker we have on Centos 7 is too old. @phracek do I understand it correctly that the only thing we need to do is to switch this
https://github.com/sclorg/s2i-python-container/blob/6dddc3a596344202d92c6454f6fa21a63924a853/.github/workflows/docker-tests.yml#L16-L21
to Centos stream 9: https://github.com/sclorg/sclorg-testing-farm/blob/main/plans/c9s.fmf ?

**Comment by phracek** [comment]
I will fix it soon. it is on my plan.
