### ISSUE TITLE
Build and push action is broken

### ISSUE THREAD

**Issue by frenzymadness** [sclorg/s2i-python-container#513]
Hi @phracek . I was looking for Fedora images on Quay.io when I discovered that the build and push action does not for 2 months here, see https://github.com/sclorg/s2i-python-container/actions/workflows/build-and-push.yml

An interesting part of the log says:
```
 "python-39-39" was found in the Podman image storage, but not in the Docker image storage. The image(s) will be pushed from Podman image storage.
Pushing "python-39-39" with tags "latest, 39, 27c97427ae751ff64938a8a63c58079ba2fb649b" to "quay.io/fedora" as "***"
/usr/bin/podman push --quiet --digestfile python-39-39-latest_digest.txt python-39-39:latest quay.io/fedora/python-39-39:latest --tls-verify=true --creds=***:***
Error: trying to reuse blob sha256:883e787c00d4208d75fc3e85d100ce64b517e49a2468f0e7f084cf05d16f3e46 at destination: checking whether a blob sha256:883e787c00d4208d75fc3e85d100ce64b517e49a2468f0e7f084cf05d16f3e46 exists in quay.io/fedora/python-39-39: unauthorized: authentication required
Error: Error: podman exited with code 125
Error: trying to reuse blob sha256:883e787c00d4208d75fc3e85d100ce64b517e49a2468f0e7f084cf05d16f3e46 at destination: checking whether a blob sha256:883e787c00d4208d75fc3e85d100ce64b517e49a2468f0e7f084cf05d16f3e46 exists in quay.io/fedora/python-39-39: unauthorized: authentication required
```

**Comment by zmiklank** [comment]
Hi, there are various reasons for the failures. Few of them are already fixed by:
1) https://github.com/sclorg/s2i-python-container/pull/520
2) https://github.com/sclorg/s2i-python-container/pull/509

However, there is still more.

**Comment by zmiklank** [comment]
@frenzymadness 
All build-and-push related bugs are fixed now, only the Fedora with python 3.10 is failing on build of container image:

`Failed loading plugin "needs_restarting": [Errno 40] Too many levels of symbolic links: '/usr/lib64/python3.10/xml/__init__.py'`

**Comment by frenzymadness** [comment]
I'm gonna try to build the image locally. Thanks for letting me know.

**Comment by frenzymadness** [comment]
It seems that the build and push action works well again. Thanks for all the fixes!

https://github.com/sclorg/s2i-python-container/actions/runs/2426819587
