### ISSUE TITLE
Python-27 for RHEL7 reached EOL

### ISSUE THREAD

**Issue by phracek** [sclorg/s2i-python-container#536]
Python-27 for RHEL7 reached EOL.

Please update README.md and dist-gen files accordingly.

**Comment by frenzymadness** [comment]
Are you sure? I mean, Python 2 is the main Python interpreter in RHEL 7 and the OS itself is supported till 2024 IIRC. I cannot find any info about the python-27 collection tho.

**Comment by frenzymadness** [comment]
Ah, you are right! I see it now here: https://access.redhat.com/support/policy/updates/rhscl-rhel7

**Comment by pkubatrh** [comment]
The SCL is EOL, though I am planning to double check that to make sure it is correct. Another question is if we want to move the python 2.7 image to the native python version available in RHEL7.

**Comment by frenzymadness** [comment]
I wouldn't do that. The native Python 2 version is very old and that'd mean a downgrade in the context of the container image.

**Comment by pkubatrh** [comment]
Confirmed the SCL is EOL and we can go ahead to deprecate the image.
