### ISSUE TITLE
https connections with unknown CA cert

### ISSUE THREAD

**Issue by jim-minter** [sclorg/s2i-python-container#55]
At the moment sti-python's assemble script appears to honour https_proxy, but pip dies if the proxy's CA cert is unknown.  sti-perl, by comparison, honours https_proxy and appears not to worry about unknown proxy CA certs.

It would be handy to be able to pass in an additional trusted CA cert without having to go to the hassle of rebuilding sti-python.

**Comment by bparees** [comment]
@sYnfo are you still intending to work this issue?

**Comment by jim-minter** [comment]
https://github.com/RedHatEMEA/demobuilder/blob/master/layers/rhel-server-7:gui:ose-3.1:offline/%40target/registry.access.redhat.com/rhscl/python-34-rhel7/Dockerfile might be of interest here for reference. It:
a) works around this issue (pulls in the CA cert out of band and calls pip with a --cert argument)
b) works around https://bugzilla.redhat.com/show_bug.cgi?id=1255516 , which prevents pip from working correctly behind a HTTPS proxy.  It wouldn't hurt if you could lean on the RHSCL folks to get the backport indicated in the bz applied!

**Comment by frenzymadness** [comment]
Is this still relevant? I don't see any usage of `https_proxy` in the current Python container.

**Comment by frenzymadness** [comment]
Please reopen if this still affects you.
