### ISSUE TITLE
Poetry backed project is not installed

### ISSUE THREAD

**Issue by shifqu** [sclorg/s2i-python-container#560]
Hi, thanks for this awesome repository.

Recently within our team, we switched to use poetry.

Now, when using the s2i on our openshift environment (coupled with env var USE_MICROPIPENV=1) the application builds properly, but once the run command is triggered, we receive a `ModuleNotFoundError` stating that the root package is not found.

After some debugging, I noticed that the problem here might be [this line in the assemble script](https://github.com/sclorg/s2i-python-container/blob/master/3.9/s2i/bin/assemble#L88). It only runs `pip install .` whenever a setup.cfg or setup.py file is found. Since the addition of pyproject.toml, pip can also handle that.

Therefore, I think the assemble script could be expanded to not only check for the presence of setup.py or setup.cfg, but also include pyproject.toml

If you see any issues with this proposal, do you have a way for us to run the `pip install .` right after calling assemble, but before calling run? When attempting to override the dockerfile and adding the `pip install .`, this command is run BEFORE calling the assemble script, so that is not a solution either.

INFO: We use the python39 ubi8

If there is further information I can provide, feel free to ask for it :) 
Hope to hear from you soon.

Kind regards

**Comment by shifqu** [comment]
Hi @frenzymadness , thanks for the fast response.

Indeed, I guess in order to support the pyproject.toml the condition should be that `! -z "$UPGRADE_PIP_TO_LATEST" && -f pyproject.toml`.

So far, I do not have a public project for this. But I suppose I could make a public poetry project. Just not sure how to test the s2i build for it.  
Would it be sufficient if I created a public repo that has a minimal poetry project in there? (With poetry project, I mean a project that uses pyproject.toml)

**Comment by shifqu** [comment]
I have just created a minimal poetry project and made it public.
I added requests as a main dependency and black as a dev dependency.
I didn't use any proxy for the requirements, so this repo should be usable by anyone.

If there is anything else I could add to make the s2i usage more easy, let me know and I will (try to) add to this project.

The project: https://github.com/shifqu/minimal-poetry

**Comment by frenzymadness** [comment]
Thanks for the example. I'm testing it now. Could you please help me understand what kind of import didn't work for you when the app itself is not installed? When I build a container image with the example project, I see it in the working directory so `import minimal_poetry` should work.

What I've tried is to have these modules in the minimal_poetry package:
a.py with some content:
```python
foo = 8
```
b.py with a relative import:
```python
from .a import foo
```
c.py with absolute import:
```python
from minimal_poetry.a import foo
```

And it seems that all of them works fine:
```python
>>> from minimal_poetry import a
>>> from minimal_poetry import b
>>> from minimal_poetry import c
```
The reason is that CWD `/opt/app-root/src` is in PYTHONPATH and therefore all packages from that path are importable.

**Comment by shifqu** [comment]
Thanks for testing this!
So I checked again and apparently, I had left out an important detail of our setup, which is that we use a `src` layout. I recreated the minimal_poetry package [minimal-poetry-src-layout](https://github.com/shifqu/minimal-poetry-src-layout). This was done by running `poetry new $ProjectPath --src`. 
I also included the a, b and c files already and once again added requests as a regular dep and black as a dev-dep.

Could you try again with this set-up?

Maybe  there is an ENV var that we can set? Like $APP_HOME? I have tried setting the APP_HOME, but then I still get the ModuleNotFound error. I suppose this is because in the `run` script we add `pwd` to the path before we cd into app_home.

I think maybe the title of this issue should become something along the lines of `Cannot use absolute imports in poetry project with src-layout`

Apologies for not mentioning the src layout earlier, I had thought it was merely a detail 🤦‍♂️ 

Also, since this is quite an exotic scenario (poetry in combination with src layout), I would understand if you'd lower the priority on this. We currently work around this by shipping our repos with an assemble script as I mentioned in an earlier comment.

**Comment by frenzymadness** [comment]
I had the solution since the last week but I hoped I'll be able to test a new CI config on it. It seems that the new CI will take much longer so I've opened #575 to not block this. Would you mind taking a look at the proposed solution?

**Comment by shifqu** [comment]
Thanks @frenzymadness! I reviewed and put my stamp of approval on the PR :)
