### ISSUE TITLE
Streamlit Update

### ISSUE THREAD

**Issue by dxk5271** [sclorg/s2i-python-container#563]
Hello! Thank you for this great repo and all of the great documentation. 

When building my Streamlit project in openshift I'm unable to install any version of streamlit higher than 1.12. The latest version of is 1.15.

Is it possible to add the latest Streamlit versions?

My team is currently using Python 3.9 (UBI 8).

Thank you very much.

**Comment by frenzymadness** [comment]
Hi. If this is still relevant, feel free to reopen it.
