### ISSUE TITLE
Remove verification of installed packages

### ISSUE THREAD

**Issue by frenzymadness** [sclorg/s2i-python-container#578]
We have `rpm -V` as a verification of installed packages In the Dockerfiles, like this one:

https://github.com/sclorg/s2i-python-container/blob/92131e21ddc95cc25317333f0a1e62a821dfbd56/3.9/Dockerfile.rhel9#L46

But this restriction removes the possibility to install packages by their alternative names. For example, Python 3.9 on C9S provides:
```
# rpm -q --provides python3
platform-python = 3.9.16-1.el9
platform-python(x86-64) = 3.9.16-1.el9
python(abi) = 3.9
python(abi) = 3.9
python3 = 3.9.16-1.el9
python3(x86-64) = 3.9.16-1.el9
python3.9 = 3.9.16-1.el9
python3.9(x86-64) = 3.9.16-1.el9
python39 = 3.9.16-1.el9
```
so it does not really matters whether I install python3.9 or python39 but the verification step fails in that case because the name of the RPM package is python3 and `rpm -V python3.9` fails.

My question is: Why do we need that given the fact that the dnf/microdnf fails if they get an unknown package name to install and their failure stops the build?

Any opinions @hhorak @phracek @pkubatrh @torsava ?

**Comment by frenzymadness** [comment]
Or, maybe a better question: do you recall any situation when dnf/microdnf ended with success and then the `rpm -V` verification failed for some reason and uncovered any issue?

**Comment by torsava** [comment]
I vaguely recall that the verification was useful because there were some files that mad accidentally modified permissions and this caught it.

Maybe instead of doing `rpm -V INSTALL_PKGS`, we could check *all* packages installed in the image (output of `rpm -qa`)? But maybe that fails on some missing man pages, etc., dunno.

**Comment by frenzymadness** [comment]
This is fixed for minimal container images where the problem lied.
