### ISSUE TITLE
Python 3.10 RHEL image missing in RHEL Container catalog?

### ISSUE THREAD

**Issue by sebastianbertoli** [sclorg/s2i-python-container#584]
"The RHEL images are available in the [Red Hat Container Catalog](https://catalog.redhat.com/software/containers/explore)"

@frenzymadness I cannot find the RHEL Python 3.10 image in the Red Hat Container Catalog. Could you kindly point me in the right direction? Thank you! :)

**Comment by pkubatrh** [comment]
There is no RHEL-based Python 3.10 image, because no version of RHEL ships Python 3.10.

**Comment by pkubatrh** [comment]
Note that we should have Python 3.11 available soon in c8s and c9s: #583

**Comment by sebastianbertoli** [comment]
Awesome, thanks! :)
