### ISSUE TITLE
tests: test case should fail early when the prepare function fails

### ISSUE THREAD

**Issue by pkubatrh** [sclorg/s2i-python-container#593]
I encountered this specifically when the image was not available (forgot to pull it from registry). The test suite prints out an error (https://github.com/sclorg/s2i-python-container/blob/master/test/run#L85) but continues running since the return value is never checked.

**Comment by frenzymadness** [comment]
PRs welcome :wink:

**Comment by zmiklank** [comment]
Yes, currently is not possible to simply end the testsuite, if the preparation is not possible.
Therefore the prepare function return 1 and it gets [FAILED] flag in the results.
However, the bug that I see here is, that it does not TESTCASE_RESULT to 1 so in theory the testsuite could still succeed. (Is this also the core of issue you encountered?)

However, as the app image could not be properly build I think the rest of the tests would fail anyway, and also fail the testsuite. Or haven't they?

I agree, that we should fix this. But we should, IMO, do it properly and do not run more tests for this app if the image build fails.

**Comment by zmiklank** [comment]
We should also find out, if this is python-specific, or we should adjust also some other containers. I did not look into that yet.
