### ISSUE TITLE
Distgen errors

### ISSUE THREAD

**Issue by zmiklank** [sclorg/s2i-python-container#594]
Distgen is throwing errors while generating content for s2i-python container.

Logs can be seen when running localy (`make generate-all`) or in CI[1].

[1] https://github.com/sclorg/s2i-python-container/actions/runs/4383184504/jobs/7673113942

**Comment by frenzymadness** [comment]
`make generate-all` tries to generate all combinations but only a subset of them is defined in multispec file. The errors are just complains that a specific combination is not defined in the multispec. Does that cause any troubles?

**Comment by frenzymadness** [comment]
For example, `manifest.yml` says that we should generate Dockerfile.centos7 for all Pythons but in multispec, there is no combination of Python 3.11 on Centos 7.

**Comment by zmiklank** [comment]
> If distgen has a special error code for the cases of missing combinations in the matrix, we can update generator to ignore that specific error. 

I like this. But I would say this is of not very high priority. Thanks for the analysis.

**Comment by frenzymadness** [comment]
I've prepared an implementation for distgen which should allow us to safely ignore some types of errors from distgen.

**Comment by frenzymadness** [comment]
So the distgen part is done and released: https://github.com/devexp-db/distgen/pull/130 . @befeleme is this something you'd be interested in? This has to be implemented in the common scripts so you might gain some hands-on experience with submodule synchronization and testing of changes there. The change itself should not be complex.

**Comment by befeleme** [comment]
I'll look at this, thank you!

**Comment by befeleme** [comment]
What's the desired action generator should do when encountering exit code 2? I'm thinking of suppressing the error message, so this would not be printed at all: `[ERROR] distgen failed: Command '['dg', '--multispec', 'specs/multispec.yml', '--template', 'src/Dockerfile.template', '--distro', 'rhel-9-x86_64.yaml', '--multispec-selector', 'version=3.11', '--output', '3.11/Dockerfile.rhel9']'`.
Would you like to have some other message printed instead?

**Comment by frenzymadness** [comment]
> What's the desired action generator should do when encountering exit code 2? I'm thinking of suppressing the error message, so this would not be printed at all: `[ERROR] distgen failed: Command '['dg', '--multispec', 'specs/multispec.yml', '--template', 'src/Dockerfile.template', '--distro', 'rhel-9-x86_64.yaml', '--multispec-selector', 'version=3.11', '--output', '3.11/Dockerfile.rhel9']'`. Would you like to have some other message printed instead?

I think we discussed it yesterday so just FTR I believe that suppressing the error is all we need.

**Comment by zmiklank** [comment]
This feature is AFAIK already implemented and works well. Thanks all for the work on this. Closing.
