### ISSUE TITLE
Support gunicorn >=20.1.0 defaults (do not require APP_ environment variables)

### ISSUE THREAD

**Issue by kpfleming** [sclorg/s2i-python-container#599]
### Container platform

Podman/Docker

### Version

Latest code in repo, this is a feature request.

### OS version of the container image

RHEL 7, RHEL 8, RHEL 9, CentOS 7, CentOS Stream 8, CentOS Stream 9, Fedora

### Description

As of version 20.1.0, Gunicorn has a default for its `config` parameter, which is `gunicorn.conf.py`. In addition the `wsgi_app` parameter can be set there.

As a result, with a sufficiently new version of Gunicorn, there are no environment variables or command-line parameters required at all to properly start the application.

Given that, I think it would be useful for the owner of the application being packaged to be able to control the `wsgi_app` directly in their code repository, and not have to ensure that `APP_MODULE` or `APP_CONFIG` are set properly in their execution environment (or provide an `.s2i/environment` file which sets one of them). This keeps all of the knowledge of how to start the application in 'normal' Gunicorn locations, so that it can be started manually or in an s2i-created image in the same way.

Presumably the `run` script would need to verify that the Gunicorn version is high enough, and that `gunicorn.conf.py` exists and that `wsgi_app` is set in it, before deciding to start Gunicorn in this 'bare' fashion.

**Comment by frenzymadness** [comment]
I would appreciate a PR or any other help with this. I understand how useful it might be but because it doesn't really cause any problems it's not high in my ToDo.
