### ISSUE TITLE
Add RHEL images for Python 3.11

### ISSUE THREAD

**Issue by tonycosentini** [sclorg/s2i-python-container#600]
### Container platform

Podman/Docker

### Version

N/A

### OS version of the container image

RHEL 8, RHEL 9

### Description

It looks like RHEL support Python 3.11 now. It would be nice to have RHEL images for this Python version if possible.

**Comment by frenzymadness** [comment]
Thanks for the issue. You are 100% right. I'm gonna add sources for the container images here soon. If you need to use them immediately, you should be able to find them already in Red Hat catalog: https://catalog.redhat.com/software/containers/search?q=python-311&p=1

**Comment by frenzymadness** [comment]
I've just merged Python 3.11 for RHEL 9.

**Comment by tonycosentini** [comment]
Thanks @frenzymadness!
