### ISSUE TITLE
Use PIP_INDEX_URL with pipenv

### ISSUE THREAD

**Issue by gardar** [sclorg/s2i-python-container#654]
`pipenv` does not read the `PIP_INDEX_URL` environment variable (see: https://github.com/pypa/pipenv/issues/4808 ) so to when using a local pip mirror I have to define the mirror url twice, both with `PIP_INDEX_URL` env var (for installing `pipenv`) and also in the `Pipfile`.
While it's not a huge problem it would still be nice to be able to configure the mirror with a single env var.

I see two possible solutions:

To either pass the value of `PIP_INDEX_URL` to the `pipenv install` command with the `--index` option
```   
pipenv install --deploy --index $PIP_INDEX_URL
```

or write the `PIP_INDEX_URL` env var to a `pip.conf` or `pip.ini` during the assemble.

**Comment by frenzymadness** [comment]
@hrnciar this is something you might be interested in. Seems like an easy fix.
