### ISSUE TITLE
ubi9/python-311:latest is using python3.9-rpm

### ISSUE THREAD

**Issue by dichn** [sclorg/s2i-python-container#657]
### Bugzilla, Jira

https://github.com/release-engineering/ubi-manifest/pull/106

### Description

Hey team,

Our team is using ubi9/python-311:latest as base image to build our application image, and we highly depends on the os-level python module python3-rpm. But the ubi9/python-311:latest image has a python3.9-rpm installed.

```
$ podman run -it registry.access.redhat.com/ubi9/python-311:latest /bin/bash
(app-root) rpm -ql python3-rpm
/usr/lib/.build-id
/usr/lib/.build-id/4f
/usr/lib/.build-id/4f/139a492a833ff86aeb7e0581c51a7dbe49227f
/usr/lib64/python3.9/site-packages/rpm
/usr/lib64/python3.9/site-packages/rpm-4.16.1.3-py3.9.egg-info
/usr/lib64/python3.9/site-packages/rpm/__init__.py
/usr/lib64/python3.9/site-packages/rpm/__pycache__
/usr/lib64/python3.9/site-packages/rpm/__pycache__/__init__.cpython-39.opt-1.pyc
/usr/lib64/python3.9/site-packages/rpm/__pycache__/__init__.cpython-39.pyc
/usr/lib64/python3.9/site-packages/rpm/__pycache__/transaction.cpython-39.opt-1.pyc
/usr/lib64/python3.9/site-packages/rpm/__pycache__/transaction.cpython-39.pyc
/usr/lib64/python3.9/site-packages/rpm/_rpm.cpython-39-x86_64-linux-gnu.so
/usr/lib64/python3.9/site-packages/rpm/transaction.py
```

Could you please upgrade the python3-rpm to python3.11-rpm?

**Comment by frenzymadness** [comment]
Hello. Thanks for the report. I'm afraid that it's not possible to do what you are asking for. Let me explain.

Every RHEL release contains one main Python interpreter and some alternative Python stacks. The main Python is supported for the whole support span of the given RHEL release (alternative Pythons have shorter and limited support). All system tools (like anaconda, dnf, rpm) have to use the main Python interpreter. We provide the alternative stacks for application developers with a limited set of RPM packages but they usually install dependencies from other sources like PyPI.

Python bindings for RPM are provided by the `rpm` package and those bindings are currently built only for the main Python interpreter and we don't plan to provide the subpackage for alternative Python stacks.
