### ISSUE TITLE
Publish arm64 images

### ISSUE THREAD

**Issue by tonycosentini** [sclorg/s2i-python-container#659]
### Container platform

Podman/Docker

### Version

Non-RHEL images hosted on Quay.

### OS version of the container image

CentOS Stream 9

### Description

Is it possible to start publishing arm64 images to Quay? I was planning on switching off of UBI8 and onto c9s, but there is no arm support.

UBI 8 example:
```
➜  docker manifest inspect registry.access.redhat.com/ubi9/python-311     
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 926,
         "digest": "sha256:9101b9924d06a4944649e9cb008496813479d66271ee1f2a1b6ddfc91228c97c",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 926,
         "digest": "sha256:d4b195e9afabfd9184f7d6ca58a5358ff9b11d6367d61c2d587bb6c695671097",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 926,
         "digest": "sha256:5eaecbc30e36eaf5c60c43515a1453af10df77f2c483535432eb66b656e1cf7a",
         "platform": {
            "architecture": "ppc64le",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 926,
         "digest": "sha256:36f0e63073521a14a584619d84d3c5332e05dd65f6856853fa6064992876b28b",
         "platform": {
            "architecture": "s390x",
            "os": "linux"
         }
      }
   ]
}
```

c9s example:
```
➜ docker manifest inspect quay.io/sclorg/python-311-c9s               
{
	"schemaVersion": 2,
	"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
	"config": {
		"mediaType": "application/vnd.docker.container.image.v1+json",
		"size": 16094,
		"digest": "sha256:a4469a80a000d2d24c745ab31c635ec3b0c479bf56462b1079e05f2ddccf9ae0"
	},
	"layers": [
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"size": 57769319,
			"digest": "sha256:a4fce492bde6a3b94c488710eb004997076e9fe948efab1b38a79566d55714bb"
		},
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"size": 16624490,
			"digest": "sha256:07ec094c651fd7fc83c388df7ecef7d3988ef10a5bb554cc30d5c852932b0fd1"
		},
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"size": 216161379,
			"digest": "sha256:fbe6cbc72bcfee27f8a40f7a1c94aa36907dfe21d142dd08a31049a2889bc405"
		},
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"size": 99443756,
			"digest": "sha256:4d499558816c75cd5cc0dbb50489895a04fc1598057d6353432009810001f47c"
		}
	]
}
```

### Reproducer

On an arm-based machine without QEMU (in my case, a Gravitron EC2 instance), just run:
```
docker run --rm quay.io/sclorg/python-311-c9s python --version
```

and it will fail with:
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /usr/bin/container-entrypoint: exec format error
```

**Comment by frenzymadness** [comment]
Thank you for the report. The UBI images use a different build system than images published on quay.io so this is a good question for @zmiklank and @phracek - is our build farm able to produce images for multiple architectures and a single manifest to combine them all?

**Comment by frenzymadness** [comment]
Side note: Python 3.11 is available also with UBI 9 so if you need to switch from UBI 8 to 9, you can do it already.

**Comment by zmiklank** [comment]
>  is our build farm able to produce images for multiple architectures and a single manifest to combine them all?

Sure, some of [postgresql images](
https://quay.io/repository/sclorg/postgresql-15-c9s?tab=tags) are already shipped in multiple architectures. 
The [patch](https://github.com/sclorg/postgresql-container/blob/3f3a6195f4638190895a0277211a8690fc7a7820/.github/workflows/build-and-push.yml#L121) for this is an easy one, if nothing goes wrong :).


We, in general, try to stick with x86_64 arch. But building postgresql images for multiple architectures has been working for some time now, and it has not brought much burden for us.

Please note, that there is no plan to run the testsuites for for other than x86_64 archs.

**Comment by frenzymadness** [comment]
> Side note: Python 3.11 is available also with UBI 9 so if you need to switch from UBI 8 to 9, you can do it already.

That being said, we usually add centos stream first because it's available sooner but we're inclined to provide better support for UBI images. Is there any reason you cannot use UBI 9?

**Comment by tonycosentini** [comment]
> > Side note: Python 3.11 is available also with UBI 9 so if you need to switch from UBI 8 to 9, you can do it already.
> 
> 
> 
> That being said, we usually add centos stream first because it's available sooner but we're inclined to provide better support for UBI images. Is there any reason you cannot use UBI 9?

There's a bug in 3.11.5 that's fixed in 3.11.6 and above.

c9s has 3.11.7 now, but my understanding is that it will be some time until it's in RHEL.

**Comment by frenzymadness** [comment]
> c9s has 3.11.7 now, but my understanding is that it will be some time until it's in RHEL.

Correct. 3.11.7 will be a part of the next RHEL 9 release.

**Comment by zmiklank** [comment]
s2i-python arm64 images are available in quay.io now.

**Comment by tonycosentini** [comment]
Wow, crazy fast turnaround - thank you!
