### ISSUE TITLE
Documented pull example quay.io/sclorg/python-39-minimal isn't a valid URL

### ISSUE THREAD

**Issue by tux-o-matic** [sclorg/s2i-python-container#679]
### Container platform

Podman/Docker

### Description

The registry for the [minimal variant](https://github.com/sclorg/s2i-python-container/blob/master/3.9-minimal/README.md) of Python 3.9 isn't publicly available.

### Reproducer

Open a browser to https://quay.io/sclorg/python-39-minimal or try to pull via Docker or Podman `quay.io/sclorg/python-39-minimal`, you'll get a 403.

**Comment by frenzymadness** [comment]
Thanks for the report. @zmiklank or @phracek could we please do something about it?

**Comment by zmiklank** [comment]
@tux-o-matic, @frenzymadness
 ```podman pull quay.io/sclorg/python-39-minimal-c9s``` works just fine for me. We provide this image for amd64 and arm64 arch. We do not provide CentOS Stream images in a  `python-39-minimal` format.

**Comment by frenzymadness** [comment]
Ou, I see. We have to fix the documentation then.

**Comment by tux-o-matic** [comment]
Indeed.
I think it’s just down to the README (of any variant, not just 3.9 minimal I guess) to give a Podman pull example to a working registry, be it CentOS 9 Stream or [RHEL8](https://quay.io/repository/sclorg/python-39-minimal-el8?tab=tags&tag=latest)

**Comment by frenzymadness** [comment]
Fix is ready for review.
