### ISSUE TITLE
Push of 3.12 container images to quay.io failed

### ISSUE THREAD

**Issue by frenzymadness** [sclorg/s2i-python-container#714]
The error is:

>  ⏳ Pushing "python-312-c10s:c10s, python-312-c10s:latest, python-312-c10s:20240924, python-312-c10s:efb348bc4d451a9ce3204044aa63c200fa4efb4a" to "quay.io/sclorg/python-312-c10s:c10s, quay.io/sclorg/python-312-c10s:latest, quay.io/sclorg/python-312-c10s:20240924, quay.io/sclorg/python-312-c10s:efb348bc4d451a9ce3204044aa63c200fa4efb4a" respectively as "***"
> /usr/bin/podman manifest push --quiet --digestfile python-312-c10s-c10s_digest.txt python-312-c10s:c10s quay.io/sclorg/python-312-c10s:c10s --all --tls-verify=true --creds=***:***
> Error: trying to reuse blob sha256:388184f84e0a7b2fd7ac01f2aaa87aef6f25e078705497001fb0356698118739 at destination: checking whether a blob sha256:388184f84e0a7b2fd7ac01f2aaa87aef6f25e078705497001fb0356698118739 exists in quay.io/sclorg/python-312-c10s: unauthorized: authentication required

and it's the same for 3.12 and 3.12-minimal on c10s.

It also seems that even though https://quay.io/repository/sclorg/python-312-minimal-c9s is publicly available, https://quay.io/repository/sclorg/python-312-minimal-c10s is not and it requires logging in.

@phracek could you please take a look?

**Comment by phracek** [comment]
Now it exists. https://quay.io/repository/sclorg/python-312-c10?tab=settings

**Comment by phracek** [comment]
The images are present in quay.io registry. https://github.com/sclorg/s2i-python-container/actions/runs/11014114579/job/30635515299 https://github.com/sclorg/s2i-python-container/actions/runs/11014114579/job/30635516316
