### ISSUE TITLE
Build support

### ISSUE THREAD

**Issue by DukeReno** [sclorg/s2i-python-container#719]
Hi, we are trying to build a Jupyter Notebook by using quay.io/sclorg/python-311-c9s:c9s (CentoOS Stream 9) as based image.
 
Currently we are facing a build issue to execute these commands
 
(cd /opt/app-root/gateway && source scl_source enable nodejs20 && \
    npm install --production)
 
Please notice that I changed the nodejs20 because this is the version of nodejs that is installed on python-311-c9s:c9s image
 
As you can see, this requires installation of centos-release-scl and centos-release-scl-rh packages for CentOS Stream 9 and We had tried to install these packages but no success so far.
 
Is there a way to execute those commands by using the based image mentioned (python-311-c9s:c9s )? Or do you know if could be possible have installed these packages for CentOS Stream 9?
 
Thanks,

**Comment by frenzymadness** [comment]
Why do you need to interact with SCL (software collections)? The nodejs version in this container image is 20.9.0 and you can run it without anything else:

```
$ podman run --rm -it quay.io/sclorg/python-311-c9s:c9s bash
(app-root) node --version
v20.9.0
(app-root) npm --version
10.1.0
```

**Comment by DukeReno** [comment]
hola, cuando tengas un chance podrias poner esto pls?
 
 
Thanks for the quick replay on this.
 
We want to update the python version to 3.11 also move from CentOs 7 to Centos stream 9 by using the image quay.io/sclorg/python-311-c9s:c9s  and We have some configuration that use SLC as described on this assemble file
 
https://github.com/jupyter-on-openshift/jupyter-notebooks/blob/develop/minimal-notebook/.s2i/bin/assemble (lines 95 and 96)
 
Is there a workaround to perform this installation steps with image python-311-c9s:c9s?
 
I have tried:
 
(cd /opt/app-root/gateway && source /usr/bin/node && \
    npm install --production)
 
But I am getting a failure message saying that "/opt/app-root/s2i/assemble: line 130: source: /usr/bin/node: cannot execute binary"                                file
 
Regards,

**Comment by frenzymadness** [comment]
I'm sorry, but it seems you don't understand what SCLs are for or what the `source` command does. Software collections don't exist anymore in Centos Stream 9 and the mentioned image contain nodejs 20 as the default one so there is no need to activate anything special or alter the environment in any way.

I think you can turn this:

```
(cd /opt/app-root/gateway && source /usr/bin/node &&
npm install --production)
```

into this:
```
(cd /opt/app-root/gateway && npm install --production)
```

This command should be enough to install nodejs packages. If it doesn't work, please provide the log of the build process.

**Comment by DukeReno** [comment]
Ok that did it, thanks for the help, the build was successful. Have a nice day

**Comment by frenzymadness** [comment]
I'm glad it did. Thank you for letting me know.
