### ISSUE TITLE
Relying on per user site-packages equivalent causes problems.

### ISSUE THREAD

**Issue by GrahamDumpleton** [sclorg/s2i-python-container#90]
The way the image is set up at present means that no Python virtual environment is used. Instead the installation of Python packages from the user `requirements.txt` file is done into the users home directory using the `--user` option to `pip`. Similarly for `setup.py`.

```
if [[ -f requirements.txt ]]; then
  echo "---> Installing dependencies ..."
  pip install --user -r requirements.txt
fi

if [[ -f setup.py ]]; then
  echo "---> Installing application ..."
  python setup.py develop --user
fi
```

Use of no Python virtual environment will ultimately cause problems and confusion for a user.

This is because when the SCL package for Python, e.g.: `python2.7`, is installed, it is dragging in as dependencies a bunch of Python packages from operating system package repository.

```
Dependencies Resolved

================================================================================
 Package                     Arch    Version              Repository       Size
================================================================================
Installing:
 python27                    x86_64  1.1-20.el7           centos-sclo-rh  4.8 k
Installing for dependencies:
 dwz                         x86_64  0.11-3.el7           base             99 k
 iso-codes                   noarch  3.46-2.el7           base            2.7 M
 perl-srpm-macros            noarch  1-8.el7              base            4.6 k
 python27-python             x86_64  2.7.8-3.el7          centos-sclo-rh   81 k
 python27-python-babel       noarch  0.9.6-8.el7          centos-sclo-rh  1.4 M
 python27-python-devel       x86_64  2.7.8-3.el7          centos-sclo-rh  384 k
 python27-python-docutils    noarch  0.11-1.el7           centos-sclo-rh  1.5 M
 python27-python-jinja2      noarch  2.6-11.el7           centos-sclo-rh  518 k
 python27-python-libs        x86_64  2.7.8-3.el7          centos-sclo-rh  5.6 M
 python27-python-markupsafe  x86_64  0.11-11.el7          centos-sclo-rh   25 k
 python27-python-nose        noarch  1.3.0-2.el7          centos-sclo-rh  274 k
 python27-python-pip         noarch  1.5.6-5.el7          centos-sclo-rh  1.3 M
 python27-python-pygments    noarch  1.5-2.el7            centos-sclo-rh  774 k
 python27-python-setuptools  noarch  0.9.8-5.el7          centos-sclo-rh  400 k
 python27-python-simplejson  x86_64  3.2.0-3.el7          centos-sclo-rh  173 k
 python27-python-sphinx      noarch  1.1.3-8.el7          centos-sclo-rh  1.1 M
 python27-python-sqlalchemy  x86_64  0.7.9-3.el7          centos-sclo-rh  2.0 M
 python27-python-virtualenv  noarch  1.10.1-2.el7         centos-sclo-rh  1.3 M
 python27-python-werkzeug    noarch  0.8.3-5.el7          centos-sclo-rh  534 k
 python27-python-wheel       noarch  0.24.0-2.el7         centos-sclo-rh   76 k
 python27-runtime            x86_64  1.1-20.el7           centos-sclo-rh  1.1 M
 redhat-rpm-config           noarch  9.1.0-68.el7.centos  base             77 k
 scl-utils-build             x86_64  20130529-17.el7_1    base             17 k
 xml-common                  noarch  0.6.3-39.el7         base             26 k
 zip                         x86_64  3.0-10.el7           base            260 k
```

This results in the following Python packages being pre installed.

```
bash-4.2$ pip freeze
Babel==0.9.6
Jinja2==2.6
MarkupSafe==0.11
Pygments==1.5
SQLAlchemy==0.7.9
Sphinx==1.1.3
Werkzeug==0.8.3
docutils==0.11
nose==1.3.0
simplejson==3.2.0
virtualenv==1.10.1
wheel==0.24.0
wsgiref==0.1.2
```

The problem now is that if a user lists in the `requirements.txt` file packages which aren't pinned to a specific version, then the latest versions of those packages will not actually be installed as they might reasonably expect. This is because a version of the package is already installed due to above dependencies.

```
$ pip install --user Jinja2
Requirement already satisfied (use --upgrade to upgrade): Jinja2 in /opt/rh/python27/root/usr/lib/python2.7/site-packages
Cleaning up...

bash-4.2$ pip freeze
Babel==0.9.6
Jinja2==2.6
MarkupSafe==0.11
Pygments==1.5
SQLAlchemy==0.7.9
Sphinx==1.1.3
Werkzeug==0.8.3
docutils==0.11
nose==1.3.0
simplejson==3.2.0
virtualenv==1.10.1
wheel==0.24.0
wsgiref==0.1.2
```

End result is that they get stuck with an older version, not the latest, and may not realise it until their application starts dying at run time.

Yes you can argue that they should be pinning the version in order to get a reproducible build, but a lot of people wouldn't do that and so would get confused as to why they aren't seeing the latest version.

In practice the only Python packages which should already be installed are `pip` and whatever it may install, such as `virtualenv`, `setuptools` and `wheel` packages. The user should not be supplied any other packages.

This is where if you can't guarantee a clean `site-packages` except for `pip` etc, a Python virtual environment should be created and `PATH` setup so that it is always used.

These days a Python virtual environment is no longer linked by default to the system `site-packages` so it will be a clean slate except for `pip` etc. One of the reasons it doesn't link to the system `site-packages` it because of confusion like this caused by the installation of Python packages from operating system package repository.

**Comment by GrahamDumpleton** [comment]
Blog post related to this topic and my own recommendations around when to use Python virtual environments in Docker.

* http://blog.dscpl.com.au/2016/01/python-virtual-environments-and-docker.html

**Comment by rhcarvalho** [comment]
I'm :+1: on using virtualenv / venv in the project and have raised this idea before, perhaps not as well explained as this issue describes the problem.

**Comment by GrahamDumpleton** [comment]
Use of a Python virtual environment could actually solve another problem. That is, it could eliminate the need to SCL enable Python in the ``run`` script or for shells using ``BASH_ENV`` and ``PROMPT_COMMAND``.

This could be achieved by removing all existing SCL enabling code and doing the following.

1. In ``Dockerfile``, set ``PATH`` to include ``/opt/app-root/venv/bin`` at the start.
2. In ``assemble``, run ``source scl_source enable pythonXY`` to enable used of SCL Python version.
3. In ``assemble``, then run ``virtualenv`` to create virtual environment at ``/opt/app-root/venv``.

When the ``pip`` is then subsequently run, because of ``PATH`` already being set, it will pick up ``pip`` from the virtual environment just created and package will be installed into the virtual environment.

When ``run`` is later run, ``python`` will also be found via ``PATH`` from the virtual environment. It shouldn't be necessary to SCL enable Python for that to work.

This also should mean that running:

```
oc rsh python -V
```

will pick up the ``python`` from the virtual environment.

Note that #96 would still be desirable for other reasons though.

**Comment by rhcarvalho** [comment]
```console
$ docker run --rm centos/python-27-centos7 virtualenv --version
1.10.1
```

```console
$ docker run --rm openshift/python-33-centos7 virtualenv --version
1.10.1
```

That version of virtualenv was released on Aug 8, 2013.

```console
$ docker run --rm centos/python-34-centos7 virtualenv --version
1.11.6
```

Released on May 17, 2014.


If we will have newer packaged versions of `virtualenv` in CentOS and RHEL via SCL I'll go ahead and make our images use a default virtual environment.

@GrahamDumpleton do you have a preference to using `venv` for Python versions that have it? If not, I prefer consistently using `virtualenv` in all images.

@hhorak @sYnfo would it be possible to get a newer version of `virtualenv` via SCL?

**Comment by GrahamDumpleton** [comment]
I would prefer to use ``virtualenv`` for all Python versions rather than using ``pyvenv`` for Python 3. There is actually a bug in ``pyvenv`` behaviour in Python 3 which means it doesn't work properly for embedded systems unless the embedded system includes a workaround for it. I have had to include a workaround in mod_wsgi so it would work anyway so it is okay, but still prefer ``virtualenv`` for all to be consistent.

BTW. If use newer ``virtualenv`` it would come with a newer ``pip`` version. So having more up to date packaged ``pip`` version may not be as big a deal. Even so ``pip`` is such an important thing that is important to keep up to date with it because of any security changes.

**Comment by hhorak** [comment]
@rhcarvalho we need to track requirements for newer versions of RHSCL packages in Bugzilla. Please, report a bug with proper reasoning why it is needed and it will be considered: https://bugzilla.redhat.com/enter_bug.cgi?product=Red Hat Software Collections&component=python-virtualenv (ideally for every SCL that you care separately).

**Comment by GrahamDumpleton** [comment]
Just hit this problem in real world case. :-(

```
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in /opt/rh/python27/root/usr/lib/python2.7/site-packages (from Flask->Lektor->-r requirements.txt (line 2))
...
Successfully installed EXIFRead Flask Lektor PyYAML argh cffi click cryptography enum34 idna inifile ipaddress itsdangerous mistune mod-wsgi ndg-httpsclient pathtools pyOpenSSL pyasn1 pycparser requests six watchdog
E0608 23:55:00.987702       1 util.go:91] + rm -rf /tmp/src
E0608 23:55:00.995379       1 util.go:91] + rm -f /opt/app-root/src/requirements.txt
E0608 23:55:01.001045       1 util.go:91] + mv /opt/app-root/src/run_lektor.py /opt/app-root/run_lektor.py
E0608 23:55:01.018828       1 util.go:91] + rm -f /opt/app-root/src/README.md
E0608 23:55:01.020415       1 util.go:91] + lektor build --output-path /opt/app-root/data
E0608 23:55:01.373292       1 util.go:91] Traceback (most recent call last):
E0608 23:55:01.373467       1 util.go:91]   File "/opt/app-root/src/.local/bin/lektor", line 7, in <module>
E0608 23:55:01.373484       1 util.go:91]     from lektor.cli import main
E0608 23:55:01.373494       1 util.go:91]   File "/opt/app-root/src/.local/lib/python2.7/site-packages/lektor/cli.py", line 9, in <module>
E0608 23:55:01.373527       1 util.go:91]     from .utils import secure_url
E0608 23:55:01.373538       1 util.go:91]   File "/opt/app-root/src/.local/lib/python2.7/site-packages/lektor/utils.py", line 24, in <module>
E0608 23:55:01.373547       1 util.go:91]     from werkzeug.urls import url_parse
E0608 23:55:01.373556       1 util.go:91] ImportError: cannot import name url_parse
```

The Lektor package requires a newer version than gets installed. Now to jump through hoops to workaround it.

**Comment by GrahamDumpleton** [comment]
Well that only got so far, then you hit problems due to ``babel`` being installed as system package.

```
E0609 00:08:13.747881       1 util.go:91]   File "/opt/app-root/src/.local/lib/python2.7/site-packages/lektor/types/primitives.py", line 10, in <module>
E0609 00:08:13.747886       1 util.go:91]     from babel.dates import get_timezone
E0609 00:08:13.747892       1 util.go:91] ImportError: cannot import name get_timezone
```

Time to give up putting hacks in ``requirements.txt`` and bootstrap in my own virtual environment to isolate it properly.

**Comment by GrahamDumpleton** [comment]
Alas shoving in a Python virtual environment cannot work because of the fact that ``pip --user`` was hardwired in the first place with no way to override it.

```
E0609 00:23:20.755124       1 util.go:91] Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
```

**Comment by GrahamDumpleton** [comment]
The only way you can workaround this problem is for a user to have a custom ``.s2i/bin/assemble`` script which includes:

```
# Create a Python virtual environment to avoid conflicts between system
# installed Python packages and what we need. We need to activate it
# straight away so is used during build and also set up shell init
# scripts so activated for a new shell as well.

virtualenv /opt/app-root

source /opt/app-root/bin/activate

echo "source /opt/app-root/bin/activate" >> /opt/app-root/etc/scl_enable

# Upgrade pip to latest version to avoid problems due to old version.

pip install -U pip

# Invoke original assemble script to install packages. Because though it
# hardwires use of a per user site-packages directory, which conflicts
# with use of a Python virtual environment, we have to edit the assemble
# script on the fly and then execute out copy.

cat /usr/libexec/s2i/assemble | sed -e 's/ --user//' > /tmp/assemble
chmod +x /tmp/assemble
/tmp/assemble
```

**Comment by pkubatrh** [comment]
Closing via #159
